### ISSUE TITLE
RAD first call always return either One or Zero record

### ISSUE THREAD

**Issue by mimiza** [amark/gun#1050]
Hi! This issued has been discussed on the Discord chat room but I still wanna create this issue here. I'm trying to implement RAD pagination and still testing it. The problem is that for the first call (after refreshing browser), it always return just 1 or no record, sometimes it's just 'undefined'. I always have to make the second call to make it work. Please take a look at the picture below.
![radtest](https://user-images.githubusercontent.com/20904034/106704676-1ce94100-661f-11eb-99ca-5f5675f7e13b.png)

**Comment by jabis** [comment]
Quoting from discord
```javascript
if((tmp = get['%']) || o.limit){
  o.limit = (tmp <= (o.pack || (1000 * 100)))? tmp : 1;
}
```
https://github.com/amark/gun/blob/master/lib/store.js#L56-L58
> jabis: 
> maybe here is the reason
> if tmp is less than or equal of the whole pack OR 1000 * 100 use tmp else 1
> store.js root.on('get' method
> so looks like your max bytes is 100000
> mimiza: 
> yeah thanks for pointing out. Actually 50k is more than enough for me. :smile:
> this should be added to docs
> jabis:
> @amark ^ something to ponder, the upper limit of rad/lex- queries is now 100k bytes, maybe there should be a store/rad-option for maximum chunk size, also if there is an o.limit already it's just ignored / overwritten here, where does the  o.pack  come from, is it some wire level package detail or?

**Comment by sirpy** [comment]
@mimiza 
i've reported this a while ago in #844 and #855 
this is a .once issue, because of two separate issues
1. relay and peers do not reply if they dont have the node
2. once has to wait X amount of time for a relay to reply and other wise if no replay in the timespan X assume there's no such node
3. .on will simply not fire at all if node doesnt exists

@mimiza a temporary solution i found was to increase to {wait:200} which usually solves the problem of course not all of the times :(
@amark this is a serious issue. we really need peers or at least relays to respond with a 'node not found'

**Comment by jabis** [comment]
@sirpy actually this is not entirely the same issue, as if you ask rad for more than 100k  bytes, it'll always return limit of 1 answer

**Comment by jabis** [comment]
![image](https://user-images.githubusercontent.com/27401/106799212-8efa6e00-6691-11eb-901a-231bf3687077.png)
altering the 1000 * 100 to 1000 * 200 in panic test results in failures

**Comment by jabis** [comment]
![image](https://user-images.githubusercontent.com/27401/106799475-e1d42580-6691-11eb-8a98-1b9ceb0a3a51.png)

**Comment by jabis** [comment]
Note it failed on `Radisk read bytes` test when I had not touched anything there 
![image](https://user-images.githubusercontent.com/27401/106799594-06c89880-6692-11eb-8291-34539682466e.png)

**Comment by sirpy** [comment]
@jabis this is not the issue described by @mimiza 
i suggest you open a different one regarding the size issue.

**Comment by jabis** [comment]
@sirpy no it's exactly the issue, if you look at his rad-call it's going over the bytelimit I specifically pointed out to you - we discussed this in discord already, when he dropped the '%': to under 100 000 bytes everything works - your `.once` issue is distinct from these RAD-specific calls, so please re-open this one, and then we can draw comparisons on the .once issue :)

**Comment by jabis** [comment]
I'll point out the call here
![image](https://user-images.githubusercontent.com/27401/106800472-14325280-6693-11eb-8f38-f52253e973a4.png)

**Comment by jabis** [comment]
@sirpy 
I would say that the first call actually subscribes to other peers (even just returning the 1 record limit set by the code above) and then second call fetches the subscribed (and locally cached) dataset - the problem is just compounded with that arbitrary 100k limit which if you over-ask will always just return 1 entry or undefined (which could be the same .once issue here) on rad-calls the `store` just does some extra limiting based on it's options

**Comment by jabis** [comment]
Last comment for this night: 
![image](https://user-images.githubusercontent.com/27401/106801525-75a6f100-6694-11eb-9fd7-175a9d1b8817.png)
