### ISSUE TITLE
SEA.work on safari generated different results for same input

### ISSUE THREAD

**Issue by i001962** [amark/gun#1052]
When this is run in Safari browser it generates different result each time it is run: 

```(async ()=>{message = await SEA.work('hello world',null, null, {name: "SHA-256"}); console.log(message);})()```

Works fine on Chrome.

Version 14.0.1 (16610.2.11.51.8)
Safari dev console. 
![image](https://user-images.githubusercontent.com/1039388/107405639-5fe26300-6abc-11eb-808b-1ec82818b5e6.png)

Also tried undefined instead of null - same result

**Comment by sirpy** [comment]
not sure why it works on chrome it shouldnt, but the second argument for work is the "salt"
if you do not specify the salt it will be random which is why you get different results each time.
here is the snippet from SEA.work
`
SEA.work = SEA.work || (async (data, pair, cb, opt) => { try { // used to be named `proof`
      var salt = (pair||{}).epub || pair; // epub not recommended, salt should be random!
      var opt = opt || {};
      if(salt instanceof Function){
        cb = salt;
        salt = u;
      }
      data = (typeof data == 'string')? data : await shim.stringify(data);
      if('sha' === (opt.name||'').toLowerCase().slice(0,3)){
        var rsha = shim.Buffer.from(await sha(data, opt.name), 'binary').toString(opt.encode || 'base64')
        if(cb){ try{ cb(rsha) }catch(e){console.log(e)} }
        return rsha;
      }
      salt = salt || shim.random(9);
`

**Comment by i001962** [comment]
Hmm. OK. So there no SEA method for hashing without a salt. 
Seems like an important capability for content addressing as instructed here - https://gun.eco/docs/Content-Addressing

I'd keep this open with the following goal:
null, null should not add salt. Unless I'm missing how one would use content addressing which is entirely possible.

```var hash = await SEA.work('hash me', null, null, {name: "SHA-256"});
gun.get('#').get(hash).put('hash me');

gun.get('#').get(hash).once(console.log);
```

To this end (has addressable content), it may be more useful to default ```gun.get('#').get(hash).put('hash me');``` to return url friendly hex.

**Comment by sirpy** [comment]
@i001962 that seems to be right.
@amark @mhelander , should we change SEA to not create a random salt by default?

**Comment by mmalmi** [comment]
Oh, it was a feature, not a bug. As a workaround, I had used a patched version of work() for Iris that only does SHA-256 hashes. Support for `null` salt should be added.

**Comment by amark** [comment]
@mmalmi correct, by default it *extends* (with random salt if not provided) else could lead to a security vulnerability in proof of work if a developer is not checking inputs carefully (they'll be vulnerable to an instant rainbow attack).

If you specify `SHA` tho then see @sirpy 's highlight, it goes into the IF and the salt is ignored (not used) and *is not random* because it never reaches the `shim.random(` call. This is safe by default because hashes are used for checksums.

That said, it does look like @i001962 's issue is that Safari *is* producing proofs of work, given the length (they're long), not hashes (they're short) despite passing `SHA` in. By chance can you `console.log(SEA.err)` after calling it? So maybe there is an issue with the options deconstructing that doesn't work in Safari? My Safari crashes entirely `=>` ES6+ not supported, so I can't test/replicate (need someone to PR a refactor to ES5).

 > (An aside: dangit, I renamed it to `SEA.work` from `SEA.proof` but now I'm realizing I probably should have kept it as `.proof(` because an extension is a proof of work, and a hash is a proof of validity - hmm, unless hashes should actually be part of `.verify(` not `.proof(` ? Tho signature verification uses asymmetry while both PBKDF2 or Argon2 are symmetric hashes that extend just like SHA/md5/etc. are symmetric hashes that *shrink* to a checksum, so they seem more like the same "category" or "family" of work. GAH! I just said "work", not "proof"... whatever we can discuss this later. Naming is just very important to me.)

**Comment by i001962** [comment]
Sea.hash seems like a reasonable function to create. Verify is like a higher order function (if you will) when comparing it to .hash  Same with .work/proof. .hash could evolve later to support multihash https://github.com/multiformats/multihash

**Comment by amark** [comment]
@i001962 I still needed you to confirm (A) did the code change fix Safari (see my above comment about me not being able to test myself)? (B) is there a `SEA.err` after the broken calls?

**Comment by amark** [comment]
Thanks for doing this on your machine, this is now fixed in https://github.com/amark/gun/pull/1062 ! :) Closing.
