### ISSUE TITLE
set adds unexpected value

### ISSUE THREAD

**Issue by smartiza** [amark/gun#1087]
I'm trying to use set when values come from `.once` but as I showed in the sample code different value will be set.

```js
var gun = Gun();
gun.get('bob').put({name: "Bb"});
gun.get('dave').put({name: "dave"});

gun.get('bob').once(v => gun.get('list').set(v))


/**
return
[object Object] {
  _: [object Object] {
    #: "list/bob",
    >: [object Object] { ... }
  },
  bob: [object Object] {
    #: "bob"
  }
}

instead of
[object Object] {
  _: [object Object] {
    #: "bob",
    >: [object Object] { ... }
  },
  name: "Bb"
}
**/
gun.get("list").map().once(v=> console.log(v))
```

**Comment by amark** [comment]
@smartiza sorry for the delay, should've brought this up on http://chat.gun.eco which is much faster for replies.

Odd. You are right, this is logging the list not the items for some reason. IDK why. But I do have it fixed in new GUN (manhattan branch), not yet published, so this will be coming! Thank you for reporting.

**Comment by amark** [comment]
@smartiza fixed in latest! :) :) :) closing.
