### ISSUE TITLE
Feature: null out a value and put in one in a single swing

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#109]
Wouldn't it be cool if you could say
`gun.path(toCollection).replace(withThisThing)`
and it would null out that value, replacing it with the passed value?

Just a thought.

**Comment by amark** [comment]
Thank you for adding this into https://github.com/PsychoLlama/gun-extensions .

Great idea, great behavior - however I don't want to support any APIs more than necessary in GUN core and these types of things should be left up to extension like the one you wrote. In fact, I hope some day that nobody actually uses the internal GUN API (because they are low level) and they instead use something like yours which abstracts/wraps things away.

Closing for now. Please reopen if you want.

**Comment by PsychoLlama** [comment]
Nope, that makes perfect sense :) Thanks for closing this!
