### ISSUE TITLE
When using gun.get("abra").put(null) with nodemon will make nodemon hang

### ISSUE THREAD

**Issue by joseDaKing** [amark/gun#1100]
When using gun.get("abra").put(null) with nodemon will make nodemon hang

**Comment by noctisatrae** [comment]
Can you give more informations ? 
Also, what is the link between `Gun` & `nodemon` ?

**Comment by noctisatrae** [comment]
Hi again ! I think we can now solve this issue.

Your code is `gun.get('abra').put(null`, right ? 

`Nodemon` crashs because this code is wrong : if you want to delete something in Gun, you need to take each key of the JSON object and make it null.

e.g : 

Imagine that your data looks like that :
```json
{
	whatever: "something",
	awesome: "data"
}
```
If you want to delete everything, you'd need to do that :
```js
gun.get('abra').put({ whatever: null, awesome: null })
```

**Comment by noctisatrae** [comment]
Hey ! 
I tried this code :
```js
gun.get('abra').put(null);
``` 
And this worked for me so I was wrong. 

But I think this code works only in certain circumstances : if you've done `gun.get('abra').put({ whatever: "you want" })`, I think it won't work.

However, if you do `gun.get('abra').put("Whatever you want")`, it'll work this time. 

Because the code to target the data is not the same in the two cases.

So, we should explain that on the documentation if it's true. Elsewhere, I'm sorry for the previous post, I was wrong ;-).

**Comment by joseDaKing** [comment]
If I write this it would hang or it would not perform the put null operation
```js
gun
.get("abra@gmail.com")
.get("name")
.put("abra")
.back()
.get("age")
.put(20)

gun
.get("abra@gmail.com")
.put(null).once(console.log)
```
```js
gun
.get("abra@gmail.com")
.put({
    name: "abra",
    age: 20
})

gun
.get("abra@gmail.com")
.put(null).once(console.log)
```

**Comment by joseDaKing** [comment]
Apparently you cannot delete root nodes that's why it wont work so I will close this issue now
