### ISSUE TITLE
how to get graph-like data out from gun

### ISSUE THREAD

**Issue by zcaudate** [amark/gun#1115]
I'm wondering how it's possible to `query` the gun database so that a nested object can be retrieved.

for example, with a relational database such a postgres, I can get graph data in json form from linked tables like this:

```
WITH j_ret AS (
  SELECT
    "id",
    "nickname",
    "password_updated",
    (
      WITH j_ret AS (
        SELECT
          "id",
          "first_name",
          "last_name",
        FROM "UserProfile"
        WHERE (
          "account_id" = "UserAccount"."id"
        )
      )
      SELECT jsonb_agg(j_ret) FROM j_ret
    ) AS "profile"
  FROM "UserAccount"
)
SELECT jsonb_agg(j_ret) FROM j_ret
```

I'm not sure how to do this with gun, especially if I want data that's deeply nested.

**Comment by zcaudate** [comment]
Is there something like a graphql interface that can pull out data from gun?

**Comment by i001962** [comment]
Best to ask question like this in chat.gun.eco

**Comment by amark** [comment]
So yes, same way graphQL adapter was built over GUN, people in past have done (tho didn't publish) SQL demos too, Mango (MongoDB query), etc..

For instance, https://gun.eco/docs/API#open `gun/lib/open.js` (tho note: not updated to latest new version just released) will return the *whole* nested object including circular references. You could modify this code to *only* load certain sub-properties (rather than all).

Things like https://gun.eco/docs/RAD#lex let you perform queries across any peers (before even loading it on your own), tho your data may need to be indexed in advanced to support this.

@zcaudate 👏  @i001962 yes please, chat is better for help / Q than github (this is meant for bugs). So I'm gonna mark this issue as "closed" (since its not a bug) and have you reference the graphql code and open.js and the chat as starting points to build - if you do, I know the rest of the community would LOVE to use a feature like this, so please PR it back :) if you're not willing to wait until somebody else builds it (tho somebody, please!!).
