### ISSUE TITLE
Is it possible to choose to ignore an update in a file based on some specific criterion?

### ISSUE THREAD

**Issue by Annorstades** [amark/gun#115]
Suppose someone was to create a decentralized login system, where the details of each user (name, city, phone etc) were stored as an encrypted, stringified JSON-object value – signed with that user's private key. This "users.json" file is then synced across all the peers in the gun-network. 

Then, one of the peers intentionally corrupts that user's details by replacing the signed and encrypted string with something else, which is then synced to all the peers. Is it possible for the other peers to ignore an update and refuse to sync if the new entry isn't, say, signed with the correct key (or any other function/criterion)?

I've only used GUN for a short while, so I may very well have missed some cornerstone of the program which renders the above question completely meaningless – but I thought I would ask anyway. :)

**Comment by amark** [comment]
@Annorstades thanks for trying out gun! Hope you've enjoyed it so far.

So first I want to clarify that there isn't really "files" with gun, but I get what you're saying.

Let's say we have this JSON-object value which has the encrypted user data in it, signed and everything, and it is getting replicated, synced, and stored on other peers.

You are correct that currently any other user could update that, since by default there isn't any security. This is not very ideal for building the type of app that you want. And there currently is another issue #47 for this.

If possible, I would like to move the discussion to that thread so it is easier for people to find the conversation. Would you please close this issue and say it has been merged to #47 ? 

An immediate response here though is: The answer is YES. This is possible, but we don't currently yet have any module/extension/framework/tool that makes it easy. Would you be willing to help work with us to build it?

Let's continue this in #47. Thanks!

**Comment by amark** [comment]
@Annorstades I hacked up an authentication demo, would love to get your thoughts on it. Could we schedule a chat?

Also could you add your project to https://github.com/amark/gun/wiki/projects ? Thanks!

**Comment by amark** [comment]
Given the new version of gun which has pretty good adapter/driver support now, plus these relating:

https://github.com/swifty/gun-p2p-auth

http://gun.js.org/explainers/data/security.html

And I'm working on an example P2P crypto social network too.

It will showcase how to use the adapter/driver hooks to reject un-signed updates.

^^ Above info should be enough to get rolling for now, so I'm gonna close this issue.
