### ISSUE TITLE
Util.text.random missing "j"

### ISSUE THREAD

**Issue by thoka** [amark/gun#124]
Its not a bug, but in the random string the letter "j" is missing.

**Comment by amark** [comment]
Well... That's embarrassing.

**Comment by amark** [comment]
How in earth did you manage to find that!??

**Comment by thoka** [comment]
Just trying to read the code to understand, what's going on inside gun ...

Some UUID generators skip some letters(for example I l), if they aim
towards human readability (without copy paste), so I think thas was the
reason, why I looked inside the string.


2015-11-17 11:45 GMT+01:00 Mark Nadal <notifications@github.com>:

**Comment by amark** [comment]
fixed in d2ee2e94b5aa11c899b59349da07647d5beb5a59 , thanks @thoka . :)

I'm impressed at how close of an eye you have. BTW, we're working on 0.3.0 which rewrites a lot of the API code that you probably just read. It fixes a ton of bugs and behavior unreliability problems. And nope, missing 'j' was not an intended readability thing, as you guessed.

I'm closing since we got this fixed. Thanks so much. Excited to get more help from you!
