### ISSUE TITLE
Just found another one - written in `go`

### ISSUE THREAD

**Issue by serapath** [amark/gun#127]
https://github.com/degdb/degdb

https://docs.google.com/document/d/1Z1zUMOGzsBLOU1JoeY-CLFI9eSMajrnQraBvSybjP8I/edit?pli=1#heading=h.pjdrauyhwww

It says it's a `decentralised graph database` and i wonder if the concept is similar to `gun` or how they differ :-)

**Comment by amark** [comment]
Cool thanks. Interesting proposition, but I actually disagree with the majority of its design and find it flawed.

From reading the doc everything is different. It is attempting to be a P2P solutions (like a Bittorent) rather than an agnostic system. Truples are common in graph databases, however both gun and Neo4J use more property graphs (while Neo4j has mandatory edge nodes, gun does not), which in my personal opinion is actually useful while triples are more of an academic thing. He chucks conflict resolution up to some fairly nondeterministic behavior that will ultimately require a lot of gossip, gun thinks this is a dangerous direction. And he also suggests that less popular content should be charged more, which I think worsens problems that already exist in things like Bittorrent, not mitigates them.

The person is obviously very smart and I hope he finds this discussion and sees what I disagree with.

Hey, @serapath would you be willing to do me a favor? Could you move this issue and the other comparison issue to a new wiki page called "comparisons"? That will make it easier for others to contribute helpful comparisons, but also have it in an easy to find location. Plus it'll allow us to reference it in these threads and close these issues. I'm wanting issues to be primarily related to code and less discussion - I'm trying to funnel discussions into the gitter and wiki. I'd really appreciate it! Thanks.

**Comment by serapath** [comment]
Ok, thx - makes sense.
Just one thought - who reads "github wikis". I prefer linked markdown files that are part of the repository a lot. People can just add a "comparison entry" through pull request which can be discussed in the open pull request and eventually merged.

Otherwise, thx a lot for your explanation.
If you want, I can try to add a markdown file `comparison.md` and link it from the main `readme.md` - but a wiki is ok too if you think that's the better approach.

Regarding `gitter`, it's awesome for discussion, i agree :-) ...as long as the results are summed up and added to the "markdown files wiki" or "github wiki" if that's the preferred way.

**Comment by amark** [comment]
Closing this now :) as it can be discussed in a comparison documentation. Trying to switch github "issues" to be about known bugs to make it easier for people using it to know about flaws.
