### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by daslicht** [amark/gun#130]
Hi,
are there any performance testes so that we can decide if GuDB is the correct solution for us.
please?

**Comment by amark** [comment]
We were just testing this with a game that was built with gun, and after some of the latest bug fixes were patched we noticed an order magnitude worse performance. So things are actually in really bad shape to be perfectly honest. However we are in the middle of v0.3.0 development which fixes these problems, like performance and we'll have some tests for them.

However, to assist you further, could you clarify what performance measurements you are looking for? **JavaScript is pretty slow**, so if you are truly looking for computational speed, gun nor JavaScript should be used. Are you wanting nodejs or browser based performance? Do you care if your render loop is choked (performance goes way down then, but you're app is responsive)? Read/write performance? Etc. ? Performance needs a context to compare to, let me know what that end goal of yours is.

I know all of them would be good, but as we work towards that I'd like to help get you numbers in the meantime. :)

Great questions/issue!

**Comment by daslicht** [comment]
Thank you for your fast reply :) 
For me Perfomance is good enough if the db can handle thousands of documents , eg a database of products and some data and a blog.

**Comment by daslicht** [comment]
Currently I am using FatFreeFramework and ReadBenPHP for my projects and just gather information if I can even make it simpler.
RedbeanPHP shares a similar very simple approach as Gun.
Do you know any other production ready database thing which supports queries as Gun or ReadBeanPHP ?
eg:
```
$post = R::dispense( 'post' );
$post->title = 'My holiday';
$id = R::store( $post );
```

**Comment by amark** [comment]
Unfortunately there is not a PHP version if gun yet (contributions welcomed!). Are you able to do browser only or use nodejs?

The upcoming 0.3.0 does a small 10k performance test, and yeah it shouldn't be a problem for what you are talking about. Actual numbers will come with that release.

Although again note, gun is JavaScript so you're never going to get serious performance like the C/C++/Assembly based databases. However those don't work in the browser and therefore involve a bunch of annoying SysAdmin and DevOps work. GUN admittedly trades performance for ease of use and fault tolerance. But yeah, what you're talking about won't be a problem, although as I mentioned the latest release had a big bad performance oopsies in it (see #120 ) but we're fixing that mistake. We're also moving away from the technique that promises uses because it was dragging performance down as well - so things will be much faster pretty soon.

So I recommend getting started with gun and we'll have it fixed by the time you're ready.

**Comment by daslicht** [comment]
No you got me wrong, I consider switching to Node, but the solution should be at lest as simple as my PHP stuff.
