### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by daslicht** [amark/gun#131]
Hi,
is there any approach how to manage permissions so that the only a specific user or group can manipulate data please?

At least a hook or middleware which runs before gun would be nice, idea?

**Comment by amark** [comment]
This depends on whether your app is P2P, federated, or centralized. See #48 and #47 .

I assume you are running a centralized service, then it is not going to be much different than using something like RethinkDB or MongoDB. You only do writes on an authorized server, and not on clients. I've started to set this up a couple times with/for other people but don't have any modules/extensions for it yet (see the other threads, because I haven't figured out the right way to generalize the problem without making assumptions about your app). This is a popular request and I happy to Skype/whatever with you to get it set up. Then if we get it working in an elegant way hopefully it is something we can then generalize into a module for everybody else who has been asking about this. I've just never found security to be elegant but I'm up to the task!

**Comment by daslicht** [comment]
Skype sounds great, If you like add me :) -> ansolas 
please

**Comment by amark** [comment]
Will do. "mark.nadal" I'm USA west coast based - actually trying to sleep in bed but texting these replies back from my phone. Let's schedule something that is good for our timezone offset. I'm generally a night owl. I'll add you tomorrow. :)

**Comment by daslicht** [comment]
Have a good night ;)
