### ISSUE TITLE
not working even in same computer between to tab

### ISSUE THREAD

**Issue by KTBsomen** [amark/gun#1376]
i just used your playground in two tabs in one i removed the set interval.I am expecting to get the realtime updates from another tab. which is not happening. even fireship made a chat app with this which is also not working. fireship is the youtuber whose video is on the docs

**Comment by amark** [comment]
which playground?

fresh installs are working, tho there does seem to be some broken relays out there so just watch out and switch to use your own or different relay URL.

**Comment by nogringo** [comment]
@KTBsomen The Fireship app did not work because he use `Gun()` without default peers, you need to use `Gun("https://gun-manhattan.herokuapp.com/gun")` and your 2 tabs will sync.

**Comment by DhavalW** [comment]
Faced the same issue & fixed it. Now it works across browsers as well, not just tabs. To be fair the playground is misleading, because you go in with the expectation that it should automatically sync by default. But it doesn't, unless you edit it and specify the peers.

Use the peers as @nogringo  suggested. Lookup the docs / quickstart or helloworld and see how the GUN object is constructed and the parameters passed. You need peers, in order to sync.

**Comment by KTBsomen** [comment]
can peerjs help as setting up peers is a daunting task

**Comment by amark** [comment]
@DhavalW 👏 👏 🙏 @nogringo , 🎊 but wait can you please just fix/contrib/wiki-update/PR a peer into the playground you're talking about? Would love for it to be more intuitive! Please add it!

Sounds like I can close this, too right? Closing.
