### ISSUE TITLE
.put() configuration

### ISSUE THREAD

**Issue by metasean** [amark/gun#138]
Currently putting on a non-existent node requires either `.set()` or `.not()`, and `.set()` has a lot of inconsistencies.

`.set()` is going to be replaced with `.init()`

Once `.init()` is working and 0.3.0 is master, we need to add in an option for `.put` (a) to default to require `.init()` `.not()` or (b) to implicitly add a node when data is `.put()`

**Comment by amark** [comment]
note: I didn't want to commit to the API name `init` necessarily.

Also an option for put... would require all the dirty logic to be baked into put (and then the problem is what about path as well?). So if we did add an option for it... it probably would just internally redirect to using the chain extension (whatever it may be called) `.init()` (as we're calling it now).

**Comment by PsychoLlama** [comment]
### method names
What to call a method that creates a collection if it doesn't exist:
- [ ] .create
- [ ] ~~.set~~
- [ ] .init
- [ ] .build
- [ ] .make
- [ ] .forge

Not to sidetrack or anything. Feel free to edit this comment and add suggestions.

**Comment by amark** [comment]
we have deprecated `.set()` and added `.init()` however its behavior is not the same as `.set()` as Sean has mentioned above `.set()` was inconsistent.
