### ISSUE TITLE
0.3.0 stack size limit trouble from time.now() in graphs

### ISSUE THREAD

**Issue by krugar** [amark/gun#152]
this appears to be a regression compared to 0.2.5, as it popped up after upgrading.

this code...

``` javascript
var Gun = require('gun')
var gun = new Gun()
var a = {x: 'X'}
var b = {x: 'Y'}

function cb(err, ok) {
  if (err) console.log(err)
}

a.foo = b
b.bar = a

var aref = gun.put(a, cb)
b.bar = aref
var bref = gun.put(b, cb)

```

...will result in:

```
Hello wonderful person! :) I'm mark@gunDB.io, message me for help or with hatemail. I want to hear from you! <3
WARNING! This `file.js` module for gun is intended only for local development testing!
projectpath/node_modules/gun/gun.js:68
                                return !o? o : JSON.parse(JSON.stringify(o)); // is shockingly faster than anything else, and our data has to be a subset of JSON anyways!
                                                               ^

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Object.Type.obj.copy (/projectpath/node_modules/gun/gun.js:68:36)
    at Object.<anonymous> (/projectpath/node_modules/gun/gun.js:1013:35)
    at Object.Type.obj.map (/projectpath/node_modules/gun/gun.js:97:19)
    at map (/projectpath/node_modules/gun/gun.js:1008:12)
    at Function.ify (/projectpath/node_modules/gun/gun.js:985:5)
    at put (/projectpath/node_modules/gun/gun.js:610:9)
    at Gun.chain.put (/projectpath/node_modules/gun/gun.js:613:5)
    at Object.<anonymous> (/projectpath/test.js:19:16)
    at Module._compile (module.js:413:34)
```

gotta love the comment :D 

how do you handle this case properly anyways (referencing an object that is stored in gun from an object you prepare for storage)? do you just drop a duplicate into gun and then slap the key to the original in-gun object on top of it? or the way i tried it up top?

**Comment by amark** [comment]
@krugar thanks for reporting this! Wasn't aware you were using GUN :) thanks for chiming in.

So quick clarification on your code:
```
var Gun = require('gun')
var gun = new Gun()
var a = {x: 'X'}
var b = {x: 'Y'}

function cb(err, ok) {
  if (err) console.log(err)
}

a.foo = b
b.bar = a

var aref = gun.put(a, cb)
```
The above runs just fine.

You then proceed to do

```
b.bar = aref
```

Where `aref` happened to be the gun reference itself. This is something **definitely should be supported** however currently is not, including 0.2.x . 

So the circular reference error that is throwing is not that the data itself has circular reference, but because you've attached a gun reference (which is function with chaining prototypes) onto your data. Functions and prototypes don't/can't get saved. I'm just wanting to check if this is what you meant/intended in the first place anyways?

**However, you are right** we should be able to support stuff like this.

I'll answer your last/second questions in a bit. What project are you working on? Would love to learn more about it and help out with anything else.

**Comment by krugar** [comment]
i'm building a bibliographic network visualization (or trying to, rather). it'll end up on github at some point and i'll ping you once theres something worthwhile to look at :)

e.g. assume we have a book and an authors
``` javascript 
some_block {
let book = { title: 'Mort', isbn: '0-575-04171-4' }
let author = { full_name: 'Pratchett, Terry', viaf: '76382712' }
book.writtenby = author
author.wrote = { by_isbn : { '0-575-04171-4': book }}
let ref = gun.put(book).key('ISBN/' + book.isbn)
ref.path('writtenby').key('VIAF/' + author.viaf)
}
``` 
assume that later, after throwing away all the variables, we stumble across another book, and alas, it is also by that same author:

``` javascript 
another_block {
let book = { title: 'Guards! Guards!', isbn: '0-575-04606-6' }
let author = { full_name: 'Pratchett, Terry', viaf: '76382712' }
book.writtenby = author
author.wrote = { by_isbn : { '0-575-04171-4': book }}
let ref = gun.put(book).key('ISBN/' + book.isbn)
ref.path('writtenby').key('VIAF/' + author.viaf) // <- does that disambiguate/merge the 2 author nodes?
}
``` 
so, at this point, how do i make gun understand that both "author" nodes are supposed to be one and the same?
what i've concluded from the 0.3.0 docs is that gun will merge nodes if i put the same key on both of them?
is there another way, or can i only disambiguate a reference / merge nodes by putting keys on them?

**Comment by metasean** [comment]
@krugar 

In your scenario, the key would pseudo-merge the two books.  There are two alternatives that won't trigger a pseudo-merge.  

Since the books are listed under the author.wrote, you can pull directly from there (e.g. `.get(author).path(wrote.by_isbn).map()`).  

Alternatively, you could use @PsychoLlama's taggerific module - https://github.com/PsychoLlama/taggerific and then use `.tag(author)` and `.tagged(author)` instead of `.key(author)` and `.get(author)`.  (@PsychoLlama is still working on it, for example it isn't passing in Jasmine and it isn't documented, but otherwise it's working.  If you have any questions, just ping him on https://gitter.im/amark/gun)

**Comment by amark** [comment]
@krugar this sounds like a perfect discussion for a Skype/Google Hangout, are you okay with that? Then I can help you out personally.

So they way you currently have it GUN isn't able to disambiguate the way you want it to. There will be two separate "author" objects in the database because the way you are saving them is document-oriented. Your bibliographic app is going to be a perfect example case of graphs, which is awesome.

I'll type up what you should do instead soon, but I'll be able to help you immediate/faster if I can just jump on a Skype/Hangouts so that way I don't have to type as much (I'm slow at typing)...

my Hangouts: aquiva@gmail.com , and my Skype: mark.nadal , what is yours?

Elsewise I'll be writing up a response on how.

**Comment by krugar** [comment]
i'm EU timezone based and i have to focus on other work tomorrow anyways, so i'm fine with the writeup version that helps everyone and not just me (and i have accounts on neither hangouts nor skype at hand right now).

**Comment by amark** [comment]
@krugar no problem.

I wrote up a working code example: http://jsbin.com/lisudikexi/edit?html,console (click run if it doesn't output console.logs on the right).

It demos how you might save/update a new/existing book and new/existing author. It demos how to link the author and the book - right now it uses a quick extension to gun that I added at top, in the future this will be built into gun by default (as I mentioned in my original post on this issue, this should be built in but sadly isn't). And then it shows a demo of how to read the data out from many different directions - from the book directly, then the author via the book; or from the author directly, then scanning over all the books by an author, etc.

I'll hopefully turn this into a writeup for the wiki all by itself. Please let me know if this was helpful/what you need. If you need anything else, we're here for you. :)

**Comment by krugar** [comment]
@amark i've tried your linkToPath plugin and it works nicely. 

however, when creating graphs of a certain size/complexity, i run into call stack size trouble with Type.time.now() ([gun.js?L121](../blob/master/gun.js#L121)), and judging from the comments in the code, you probably want to have my app/data for debugging now ;) i'll try to bundle this up in a way that does not depend on a paid-for api and throw it your way later this (EU) evening

**Comment by amark** [comment]
Hmm, interesting. Thank you for reporting this. `Type.time.now` by itself is usually not the problem, but it is the straw that breaks the camels back on some other bugs we were fixing in 0.3 - bummed to see this crop up, but good to know sooner than later. Yeah, if I could have a test case that I could use to debug that would be great. Thanks so much, sorry about this.

**Comment by krugar** [comment]
sorry i didn't get to put this up yesterday evening. 

https://owncloud.coll.mpg.de/owncloud/index.php/s/cmIFIua5yVqEsyd

this link is good until 31.01.2016 and should get you a .7z archive containing javascript + a 'dump' folder with xml files.
the code requires the babel transpiler to run, if you have `babel-node` installed globally, you should be good with just `npm install`, otherwise you need to install babel manually.

what this script does: grab one xml out of the dump folder, parse it and throw a bunch of nodes into gun, create links between some of the nodes and then repeat the same for all the other files. at least one link is supposed to be created between the nodes for each file and the rest of the graph.

**Comment by amark** [comment]
@krugar thanks, hopefully will have a follow up soon. Or have questions once I get everything opened up.

**Comment by amark** [comment]
@krugar we (separately) just started doing our battlesuite test on gun ( [panic](https://github.com/gundb/panic) ) and encountered the same error (potentially the from the exact same cause). So hopefully between your report and our battlesuite test I can get the fix out soon.

**Comment by amark** [comment]
0.5 and 0.6 represent major fixes to these old performance problems. And time.now() isn't as stupid anymore. So after a years wroth of work I'm proud to be able to close these issues!
