### ISSUE TITLE
Possible bug creating record

### ISSUE THREAD

**Issue by jtlindsey** [amark/gun#207]
```
const gun = Gun();

///////////////////////////////////////////////////////////////// Create

  const newCheckings = (user, name, accType, last4, favorite) => {
    let isoDate = (new Date()).toJSON();
    let checking = gun.put({
        name: name,
        accType: accType,
        last4: last4,
        favorite: favorite,
        status: true,
        balance: 0,
        created: isoDate
      });
    gun.get('finance').path(user).path('checkings').set(checking);
  };

  const listAccounts = (user, accountType) => {
    console.log("Query for: " + accountType);
    gun.get('finance').path(user).path(accountType).map().val((name, ID) => {
      if(!name){ return }//needed for handling null/deleted data
      // console.log(name.name, name.accType, name.created, ID);
      console.log(name, ID);
    });
  };

  const listAllObjectsForUser = (user) => {
    console.log("list all accounts for " + user);
    gun.get('finance').path(user).map().val((arg, ID) => {
      if(!arg){ return }//needed for handling null/deleted data
      // console.log(ID);
      // if ((ID === "user1") || (ID === "user2")) {// why do i get extra object without this???
        console.log(arg, "The id is: ", ID);
      // }
    });
  };

  // ADMIN ONLY
  // list all users and all their objects
  const listAllUsers = () => {
    console.log("List all users and their objects");
    gun.get('finance').map().val((arg, ID) => {
      if(!arg){ return }//needed for handling null/deleted data
      // console.log(ID);
      // if ((ID === "user1") || (ID === "user2")) {// why do i get extra object without this???
        console.log(arg, "The id is: ", ID);
      // }
    });
  };

listAllUsers();
listAllObjectsForUser('userONE');
listAllObjectsForUser('userTWO');
```

```
// localStorage.clear();
```

uncomment the below line, run/refresh window to create a record, then comment it back out.

```
newCheckings('userONE', 'Bank of America', 'Checkings', '3333', true);
```

you'll see something like this in the console

```
List all users and their objects
Object {_: Object, checkings: Object} "The id is: " "userONE"
list all accounts for userONE
Object {_: Object, q8rwd04okfWN0DiS5V1lX6Wj: Object} "The id is: " "checkings"
```

uncomment this line, run/refresh window to create a record, then comment it back.

```
newCheckings('userTWO', 'Bank of Japan', 'Checkings', '5555', true);
```

notice the record to datapath you choose is not there but something else is (bug?).
you should see something like this

```
List all users and their objects
Object {_: Object, checkings: Object} "The id is: " "userONE"
Object {_: Object, checkings: Object} "The id is: " "userTWO"
list all accounts for userONE
Object {_: Object, q8rwd04okfWN0DiS5V1lX6Wj: Object} "The id is: " "checkings"
list all accounts for userTWO
Object {_: Object, XboBf8vIb83QAhEEewB8emHP: Object} "The id is: " "checkings"
```

But instead you'll see something like this (bug?)

```
List all users and their objects
Object {_: Object, checkings: Object} "The id is: " "userONE"
Object {_: Object, XboBf8vIb83QAhEEewB8emHP: Object} "The id is: " "checkings" (<= bug?, where is userTWO id?)
list all accounts for userONE
Object {_: Object, q8rwd04okfWN0DiS5V1lX6Wj: Object} "The id is: " "checkings"
list all accounts for userTWO
```

You'll have to run the last command again to get the record you wanted but the undesired object is still there.
I noticed this in greater context and stripped the code down to the minimal needed to duplicate it.
It looks like if i create a path like `gun.get('finance').path(VAR1).path('checkings').set(checking)`
and then create another path but change VAR1, it doesn't create the desired record.
is this a bug?

**Comment by d3x0r** [comment]
sounds like https://github.com/amark/gun/issues/203

**Comment by amark** [comment]
@jtlindsey yes this looks like a bug, thanks for reporting it.

It is going to be a little bit harder for me to run through the program itself, is there anyway you could easily/quickly tell me what the data for `XboBf8vIb83QAhEEewB8emHP` (or any of the "bug" records) is?

I believe @d3x0r suspicion is correct, that the `XboBf8vIb83QAhEEewB8emHP` record is getting saved to the wrong place on the path (which is really bad!). As that is what it already looks like is the case. Knowing what the value for `XboBf8vIb83QAhEEewB8emHP` will confirm that.

This needs to get fixed. GUN should not do this. This is bad. However, if we can figure out a temporary workaround I might need to have it fixed with `0.4.x` and `0.5.x` branches, rather than in the current master/stable `0.3.x` branch. This is a really bad and severe bug, so I'll definitely be workable.

**Comment by d3x0r** [comment]
The data.json file isn't horrible to read... takes a little time to grok, but it'll identify where your data is, if it exists at all.

**Comment by jtlindsey** [comment]
@amark @d3x0r were you all able to confirm this is a bug? @d3x0r I was testing this in a project where no data.json would be generated, so all the data is in LocalStorage. Inspecting gun objects in local storage is a chore so I inspect by outputting path to console.

In my first post it looks like the first part of the path was stripped off on creation. After a object is created at `gun.get('finance').path('userONE').path('checkings')`, trying to create objects at `gun.get('finance').path('userTWO').path('checkings')`, produces this console output when iterating over data at `gun.get('finance')`: 
```
List all users and their objects
Object {_: Object, checkings: Object} "The id is: " "userONE"
Object {_: Object, XboBf8vIb83QAhEEewB8emHP: Object} "The id is: " "checkings"
```
The last line has a id of 'checkings' (should be 'userTWO') so based off the way objects are created from the code above, It looks like "userTWO" part of the path was stripped off when trying to create a object on a new path the first time (note: second attempt will create a new object on the correct path). I can confirm this by creating a method that inspects what is at `gun.get('finance').path('checkings')`

```
inspecting() {
  console.log("inspecting all");
  this.db.get('finance').path('checkings').map().val((arg, ID) => {
    if(!arg){ return }
      console.log(arg, "The id is: ", ID);
  });
};
```
and the object is there:
```
Object {_: Object, name: "Bank of Japan", accType: "Checkings", last4: "5555", favorite: true…} "The id is: " "8hvNv4Py2yeQkwoeaOLRlHTG"
```

So when i got home this morning and tried to reproduce the error using the instructions outlined in my first post in a project that does generate a data.json (electron with npm gun version 3.991) I was not able to reproduce the error. So I tried again in a project that does _not_ generate a data.json (only uses local storage) and was able to reproduce the bug. 

So it looks like this specific bug may only affect web apps that don't have a data.json or are restricted to Local Storage.

**Comment by amark** [comment]
@jtlindsey this actually makes a lot of sense, because a similar bug I fixed for @d3x0r only happened in NodeJS (where a data.json file existed). The fix was in the data.json file.js adapter, not in localStorage.

However, I'm fairly confident the bug does NOT happen with localStorage alone (I tested it here http://jsbin.com/rugudewidi/edit?js,console ).

So what I'm wondering/curious is if it specifically only happens when you are running an Electron app where both NodeJS AND Browser are running simultaneously together.

Once again, request for response: Are you able to work around this bug so we can release 0.4.x with it fixed instead of patching 0.3.x? (Actually that just gave me an idea on how I might be able to "quick fix" it for you, but I have no clue if it will actually work. So maybe I should Skype you at some point and we can try it.)

**Comment by jtlindsey** [comment]
Hey @amark you caught me just as I was about to see how many beers I could drink without blinking :-) lol. You are right about the "not happen with localstorage alone". I edited my comment after repeated test. I am also able to reproduce the bug without electron and node. Only running one instance of gundb.

I am able to work around it. If anyone else has the issue when creating a record with path like `gun.get('finance').path('userONE').path('checkings')` they can run a callback after creating a record that checks if anything is in the path `gun.get('finance').path('checkings')`. Since nothing is suppose to be at that path, they can re-attempt record creation and then write null to the unintended path.

That's the quick fix that I had reserved as a last resort. Do you know of any potential 'gotchas' with that idea?

**Comment by d3x0r** [comment]
Ya I would have done that (redo the initial create of the path...); but it turned out the data was created, but in the wrong places.  (note that's multiple, not singular)... and I didn't want other things just laying around that aren't where they were supposed to be.
It might be better to create each point along the path building up to the final store

**Comment by jtlindsey** [comment]
Hey @d3x0r I was trying to figure out how to do that yesterday and was unsuccessful. I also tried building my paths with arrays and again with dot notation. The issue still persisted. How do you create each point along the path building up to the final store?

**Comment by amark** [comment]
@jtlindsey thanks, yeah if we can roll with such a workaround it would be helpful for now. I understand this really sucks though. :(

If you also do a first-time initialize of an app's schema it could help? So like on the server the very first time it EVER boots up `gun.get('finance').not(function(){ gun.get('finance').put({users: {}, banks: {}, ...}) })` and when a user is created `function createUser(){ gun.get(USER).put({checkings: {}, savings: {}, transactions: {}, profile: {age: 0, SSN: null}}) }` ? That way you know the user's paths will always exist. Like, before adding a transaction to an account, actually knowing that the account already exists. Etc.

This is funny because I'm actually dealing with rewriting these sections/behavior in 0.4.x/0.5.x and it is an obnoxious nightmare! I'm starting to regret supporting "implicit writes" (where if automatically creates the data for you if it doesn't exist yet), however it is an amazingly useful feature of the chaining system (IF it works correctly. Ahem). But when it goes wrong, I apologize, it really skrews with you guys.

**Comment by amark** [comment]
Because this was related to https://github.com/amark/gun/issues/203 , which is now fixed... this should also be fixed. Especially since all the new versions of gun have crazy improvements to them.

Gonna close, please reopen if you ever see it again. But it looks like it is fixed.
