### ISSUE TITLE
Google Cloud Storage support

### ISSUE THREAD

**Issue by amalfra** [amark/gun#22]
How about the idea of adding Google Cloud Storage support in addition to S3?

**Comment by amark** [comment]
I was in contacts with a Google Cloud rep who was going to get me credit
for their platform, so I wanted to add this as well. But I think I lost
touch with him. I'll try and follow up with him. But yes, this should be
added, good point.

**Comment by amark** [comment]
I've messaged the guy several times now, and haven't heard back from him.

@amalfra would you be interested in helping with this? You just have to support 4 commands:

1. POST JSON data to GCS.
2. POST a redirect or an empty file that holds a pointer to the actual data to GCS.
3. GET JSON data corresponding to the redirect "key" or directly from the ID, from GCS.
4. LIST all the redirects or IDs from GCS.

Of course, having a couple extra features, like throttle/batch to help control GCS costs would be ideal, but not necessary.

**Comment by amalfra** [comment]
@smark Sure i would be delighted.

**Comment by amark** [comment]
So (4) is currently not even implemented yet, that is what I'm currently working on.

If you look at https://github.com/amark/gun/blob/master/lib/file.js you can see how a very basic GUN plugin works, specifically related to the "storage" side of the equation. What you should ALSO note is that this plugin is intended for local development only, because it has super bad performance (it flushes the entire database to file on every write). But it should be a good/clear/concise example of how simple things are.

You'll want to hook into the system in the same way that the file.js does, but you'll want to break up everything into their individual object (node), and save them independently as their own file. This is not very storage efficient, but it is much more reliable and performant.

For an example of that, look at https://github.com/amark/gun/blob/master/lib/s3.js, however it gets a little bit more complicated because it tries to throttle/batch updates. A good idea, but obviously something that can be added later.

I'd just be stoked to see a bare minimum GCS implementation, even if it is an ugly hack. And then it can get better with time / contributions. As you're working on this, please let me know what I need to document (documentation is sparse, I apologize) so that way I CAN and WILL get documentation back to you.

**Comment by amalfra** [comment]
Hi amark,

Sorry that i was looking for a way to get google cloud storage account since i don't have a credit card. Google doesn't seem to accept india debit cards.

**Comment by amark** [comment]
oh hmm, good point. I don't think I ever gave them my payment information either - I think they had a free trial or something. I'm not sure. I probably won't be able to help you out with that :(, you'd probably have to email their support.

Out of curiosity, why did you mention GUN needs to support GCS then, if you don't use GCS yourself? Obviously, GUN should support it, you are right.

**Comment by amalfra** [comment]
I would be able to help with this once i get my cloud storage account setup. I suggested GCS support as  it seemed like a worth service support.

**Comment by amark** [comment]
Yes indeed. Let me know when you get a GCS account!

**Comment by ruffrey** [comment]
fwiw, ingress to gcloud storage is free, and nearline is only $0.01 per gb per month. but they should give you credit, since this would be a nice feature :)

**Comment by Xe** [comment]
Pennies per month is nothing to debate over. If it really is a financial burden for people, contact me via email, me@christine.website.

**Comment by amalfra** [comment]
At last. Got my card added to google cloud @amark

**Comment by amark** [comment]
yay! Just in time for the 0.2.0 release, too!

**Comment by amark** [comment]
Anybody want to help write a GCS hook for GUN? The AWS S3 implementation is a good reference point.

**Comment by amark** [comment]
oops, didn't mean to close.

**Comment by amark** [comment]
Now that we are past 0.5, with v0.6 out, we're closing a lot of FAQ / "feature" request issues. GCS hooks have been asked about a couple times (not as many requests as other features though).

So because we're looking for somebody else to help/contribute this (and it isn't a gun core bug/problem) we're closing this issue. Please check out https://github.com/gundb/feature-requests though, which will be a better place to aggregate feature requests.

Thanks! I'm just hoping this helps people differentiate "bugs" form not-bugs.
