### ISSUE TITLE
Automate dependency updates

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#237]
At present, all of gun's dependencies are outdated. `aws-sdk` by 6 minor versions, and `mocha` by 2 major versions (this &ast;may&ast; be contributing to issue #235, worth checking out).

It's difficult to keep up on updates manually, so I'd recommend automating it with [the greenkeeper bot](https://greenkeeper.io/#how-it-works).

**Comment by amark** [comment]
:( because `mocha` broke support Travis testing older versions of NodeJS, I don't think we can (for now) automate dependency updates.

In fact, I'm toying with the idea of by default removing those dependencies (since gun core doesn't need them) and having them auto-install on the heroku/docker/now.sh deployments instead.

We should still probably get hooked up with greenkeeper in the future though, but for now since this isn't a bug I'm gonna close it.
