### ISSUE TITLE
what if...GunDB overcome the same as RethinkDB

### ISSUE THREAD

**Issue by BartNetJS** [amark/gun#258]
Hi

Wil GundDB in the nearby homed by a foundation like apache.org?
The reason for this question is that I have to architect solutions for enterprise grade customers.
One of the questions asked frequently is backup/support on an open source project...the what if...

For example recently RethinkdDB as a company stopped with the open source project, for an unknown reason yet.
This, of course, can happen to any project.

Tx
Bart

**Comment by amark** [comment]
Hopefully so! I will explain in more detail when I get back from my trip.

We do offer commercial/enterprise support. And would be happy to chat with you privately about that if you need to reassure clients. Send me a message at mark@gunDB.io .

**Comment by amark** [comment]
@BartNetJS back! Also messaging you privately as well about our guaranteed commercial backing, to satisfy any enterprise customers you have.

As far as the Apache Foundation, we would love to belong to them or a similar foundation. I honestly have not researched them much, so any knowledge you have please do share - or if you could help us get introduced to one. I did just meet somebody on the NodeJS committee during my trip, so I will try to remember to ask him about any ideas/connections for foundation stuff.

A large portion of the gun ecosystem is actually maintained by the community (not by any company or employee). With RethinkDB the contributors were primarily paid employees, therefore if the company failed then the project lost its support. But for gun, as a whole, this is not the case - it is more like NodeJS, even if Joyent were to fail, the community would still carry NodeJS forward. Our community is a lot smaller than NodeJS, but growing with wonderful people like you!

Obviously the biggest exception is the core of gun (which is a very tiny piece relative to the everything else in the ecosystem), and I am the https://en.wikipedia.org/wiki/Benevolent_dictator_for_life on it. So the biggest concern would be if the company behind gun (which I raised VC funding for) fails, what happens to me and gun core? I'll explain my situation quite openly:

I will build gun regardless of the company's success/failure. So even if the company behind gun (like with RethinkDB) fails, gun will still be maintained and supported (unlike RethinkDB). How can you trust me on this? Because I already have done this, I was building gun before I ever had funding or a company around it. My history is evidence of how I will behave in the future. Now the question is why would I do this? The answer may be a bit surprising: I do not like programming or databases, but they are roadblocks to the things I do like and need. As a result, I cannot achieve my goals unless I program a database like gun. Building gun is not optional for me, it is necessary. It is not something I am doing just because it is a paying job, it is something I do in order to solve more important problems in my life. As a result, gun is here to stay even if the company fails.

But guess what! There is a community AND a company around GUN. Which makes it even better for both developers and enterprise alike! So please let us know how we can help. :) I hope this answers your question.

**Comment by BartNetJS** [comment]
@amark  I really appreciate your work on GunDB.
My plan is to use GunDB on a personal project first(building a FoodComputer based on http://openag.media.mit.edu/).
And then propose GunDB to a customer on a new project.

But about my personal project, the food computer.
They (OpenAG) have all software up and running, but as nerdy I am, I’m trying to rebuild all the software with javascript based api’s

One of the api's I’m using is node-red (http://nodered.org/) in combination with Johnny-five (http://johnny-five.io/) to glue the bits and bytes together.

This is already working fine. I can manage in a graphical way all my sensors, and react on the data and expose it in one or another form (endpoint, mail,..).

The next idea is to use GunDB to store sensor data.
But, of course, it is a lot of data.
The first option I have is to reduce the data in node-red, before saving it to GunDB.
But then it is more or less on the device sitting nearby the sensors (in my case a RaspberryPi)
Hard to tweak if you have to manage a lot of them. 
An option is to set parameters in a database to tweak the reduce function
But it feels all plumbing code

So my question :-), is it possible to hook into the save process on the “virtual“ server side of GunDB in one or another way?

This is the way I think about it:

Let’s say I have temperature data that is streamed into GunDB 

On the IoT device/platform:
* SensorData=>Node-Red(Johnny-five)=>GunDB.Save()

On the server side of GunDB:
* SensorData=>GunDB Plugin(table, reduce)=>GunDB store

GunDB Plugin  is then the custom plugin where the reduce function will take place
* Table is where you apply the reduce function

Suppose the GunDB endpoint is on the RaspberryPi nearby the sensors, the reduce function is still living there, but already abstracted away from the implementation details on node-red

In a next step, it would be interesting to have this plugin also distributed over GunDB decentralized concept

So lets say:
On the RaspberryPi:
* SensorData=>Node-Red=>GunDB.Save()

On the server side of GunDB:
* SensorData=>GunDB Plugin(reduce)=>GunDB store

On a admin application where you can manage the reduce functions
* GunDB.GetPlugins(table) gives all the registered plugins on a table
* GunDB.SavePlugin(table, plugin name, reduce) => this will distribute the reduce function to the other distributed instances of GunDB

Thus this idea make any sense?

**Comment by amark** [comment]
@BartNetJS thank you so much for your compliments!

That sounds like a great plan!

Wow, what an interesting idea. I'm fascinated how johnny five (I thought it is a robotics library) and nodered (which I thought was a visual-flowchart programming library) combine to get a food computer!? Either way, sounds way cool!

Is the limitation on storage because it is a Raspberry PI and it has limited space so you need to reduce how much is storage? Or is the limitation gun? Because if gun is the limitation then we need to fix that! That would be a bug that we need to fix.

Yes! You can hook into the save process on the server.

From what I understand though, is you are wanting to dynamically add and remove hooks, correct? You might actually be more interested in PANIC, our distributed testing framework: https://github.com/gundb/panic-server . It lets you execute arbitrary code on any/all connected computers. For security reasons we obviously only suggest this for testing purposes, but if you control all your sensors then it might be exactly what you want.

Back on the saving the IoT data though, yes that can be done. But I believe your question is more about dynamically changing plugins/code and less about the data itself. Right?

**Comment by akiato** [comment]
The question to all the one man band projects is that what if you die today or tomorrow and there will be no one to carry on your work. Maybe just a silly question, but think about it.

**Comment by amark** [comment]
GUN is split up into modules by the community. I'm primarily responsible for core, many other people are working on other pieces. The to-be-honest part is... gun is significantly less useful without the addons/plugins/modules/extensions other people have provided. The to-be-honest part is if I die today or tomorrow, yeah that would really suck BUT:

We're almost at our production-ready v1.0 stable release. When that happens it won't matter if I die or not because the system will be rock solid - anything else would be feature additions (can be done as an addon), or in worse case scenario some maintainers play around with the core code knowing that our MASSIVE test suite covers a lot. :)

Good news is GUN has customers and governments starting to roll with it, so we're in no danger of death.

**Comment by amark** [comment]
Closing this thread :).
