### ISSUE TITLE
using a faster websockets library?

### ISSUE THREAD

**Issue by pyros2097** [amark/gun#261]
Iwas just wondering about using https://github.com/uWebSockets/uWebSockets as the websocket package in gunDB as it seems to be the fastest and most memory conserving websocket library there is?
Won't it improve gunDB's performance a lot?

**Comment by amark** [comment]
@pyros2097 great suggestion! Yes that sounds like a great idea, here are a couple thoughts:

1) I'm a scientist, did you run benchmarks yourself? Just to double check, cause I did a whole talk on JS perf and making sure you validate numbers yourself: https://youtu.be/BEqH-oZ4UXI 

2) Would you be up for contributing? GUN is modular, and our goal is to have a bunch of different socket adapters over time (low level ones and high level ones, Socket.io, SockJS, etc.) that people can choose what fits best. You should be able to swap it out yourself (although admittedly the current websocket adapter is pretty ugly, so you might have to complain at us for help), the probably most important piece is this file: https://github.com/amark/gun/blob/master/lib/ws.js , if you can roughly match this, only a minor patch afterwards I think would have to be done to make everything work (I hope at least, definitely want to make this easier).

3) Replacing adapter libraries is, on my own priority list, pretty low (compared to things like finishing 0.5, building a SQL query layer, and helping others in the community with finishing up auth tools). So I won't be able to volunteer to do the work, but if others can I'll definitely do my best to help with any hiccups!

What are you working on? :)

**Comment by pyros2097** [comment]
I'm a Web/Game Developer. So performance is really critical to me from the games perspective.

1. I haven't yet run the benchmarks.

2. Yeah I was wondering why you didn't make the socket implementation pluggable. Maybe something like primus will suffice here. I don't think I have the time immediately but will have some in the future and would be able to play around with it and trying to integrate uws or primus into it.

3. Agree that these features are more important. Querying is vital.

I'm working a CMS like SPA site. Its based on react and relay and uses graph.cool as the BaaS. But I like the approach of offline first and distributed p2p database as a backend and was going to try and see how much perf it improves. Because every time my page loads it makes a request to fetch all the data and that takes time.

I was looking through, since gunDB is a graph it almost resembles relay is some sense that it also maintains nodes, edges to improve caching and perf, latency, etc. So wanted to know if my application will benefit from gunDB.

I really like the idea of decentralized database. Generally in a web app the main point of failure is the database (even performance wise) so we need to implement high level caching and replication layers which makes the dev life harder.

Some more questions,

1. Can I have multiple server hosts for gunDB? (basically docker containers on different hosts)
2. Why didn't you implement this is go or rust since they seem to be better for systems programming? I have seen the rust websockets library scored the highest among most other implementations.

**Comment by amark** [comment]
@pyros2097 oolaalaa that is awesome, have any game demos or prototypes? Well you will be very happy to hear that the bleeding edge 0.5 version of gun can do 30M+ ops/sec and even be running at millions of ops/sec on low end devices like phones: https://github.com/amark/gun/wiki/100000-ops-sec-in-IE6-on-2GB-Atom-CPU .

The reason why we did this is because somebody built a game with gun and I was like "holy cow the frame rate is terrible, is that gun's fault?" and decided to get our butts in gear and deliver insanity level performance improvements. So I'd love to have you be able to push the limit on stuff (still all a Work in Progress, but ya know)!

(2) it is pluggable, just not lacking TLC and documentation since it is low priority. :P

I'm not familiar with relay but my go to question would be... does it provide browser to browser sync? If so, woah that sounds cool! If not, then gun and it might go hand in hand. Gun does cross-device sync and relay does the UI?

Absolutely, man, spot on. That is literally the pitch of gun every time I meet investors, "the database is the single point of failure"! You're nailing it. My goal is to improve gun to the point it can be handling thousands (and more) of concurrent connections like butter (which is where perhaps uWebSocket might help), so much that we've even built a distributed testing framework to generate and simulate high loads and test data sync and integrity: https://github.com/gundb/panic-server . We ran an internal test on a storage layer for gun and were able to process over 100M+ records a day for just $10 total cost for all processing, disk, and backup for about 100GB of data! And that is hopefully just the start.

(1) Yeah! Can even do crazy things like this: continuous live auto failover across the multiple server peers: https://youtu.be/-FN_J3etdvY
(2) They are! But that is part of why I didn't weirdly enough. I wanted to choose a language that would have the most failure conditions, this would force me to be testing the database under the worst possible conditions all the time and force me to develop fault tolerant resilient systems. Once that is figured out (and it is almost done! Hopefully a stable production ready release in the next 6 months) it will be trivial to implement it in a **ahem** real programming language, and the performance gains will be absurd!

Just gotta make sure the base system can survive anything though, even JS ;).

**Comment by d3x0r** [comment]
Somewhat a question of premature optimization perhaps; however, this performance is important to me also; though I think the translation from json to object will dwarf the percentage gains for any websock.  
  But it IS pluggable; so if it should get to be a bottleneck, it can be replaced... 
I've used it roughly as a direct interface at 60fps and it generally kept up actually... though to ease up I throttled updates significantly.... so I think the pipe you're transmitting on will probably bottleneck before websock can really; but time will tell... It's kinda a mockup for now; but turns out the interface from gun-space to io space is pretty slim and easily re-plugged....
Somewhat a question of premature optimization perhaps; however, this performance is important to me also; though I think the translation from json to object will dwarf the percentage gains for any websock.  
  But it IS pluggable; so if it should get to be a bottleneck, it can be replaced... 
I've used it roughly as a direct interface at 60fps and it generally kept up actually... though to ease up I throttled updates significantly.... so I think the pipe you're transmitting on will probably bottleneck before websock can really; but time will tell... It's kinda a mockup for now; but turns out the interface from gun-space to io space is pretty slim and easily re-plugged....

**Comment by alexhultman** [comment]
@amark I'm watching your video and it has to be the best JavaScript performance video I have seen so far. It truly is a joke how perf gets split in twine simpöy by calling a function with constant types.

I like the video because it shows how bad JS can be and how to avoid it rather than try to show some made up imagination land where "JS compiles to machine code". Very few JS developers actually benchmark their code, and even fewer benchmark their code against something other than their own code.

Nice work :clap:

**Comment by amark** [comment]
@alexhultman that is an honor to hear from you, thank you! Sorry for the delayed response, my entire family flew out for Thanksgiving and we were busy hosting them. Are you in Stockholm? I was in Malmö a year ago and will probably be in Stockholm in a year from now - we should meet up.

@alexhultman @d3x0r @pyros2097 good news, the latest pushes we ( @PsychoLlama ) made to the bleeding edge `0.5` branch dramatically simplifies transport layers work to plugin (we brought into core firewall/auth/security, broadcast storm mitigation/deduplication, message routing/responses), as an example for receiving messages it is as simple as:

```
ws.onmessage = function(msg){
	gun.on('in', JSON.parse(msg.data));
};
```

**Comment by alexhultman** [comment]
Are you swedish or what? I live south.

**Comment by amark** [comment]
@alexhultman no, I am not Swedish :( sadly. My wife (she does data science stuff), though, is 2nd generation Norwegian to USA (but we both agree, Swedes are nicer/warmer/friendlier), although Norway hands down has way better hiking/nature (we did kjeragbolten, preikestolen, and trolltunga). So I'm excited to hopefully go to Stockholm next year.

Hey, @alexhultman what notification system are you using that notified you of uWebSocket being mentioned in this thread? I need to steal your tools to get better myself! Mind shooting me an email so I can pick your brains on some tips, and how you got publicity for uWebSockets? Great awesome work, BTW. mark@gunDB.io

**Comment by amark** [comment]
My most recent commit started playing around with `uws` :D not at all finished. But I'm now gonna close this thread (since slower websockets isn't a "bug") and because we're moving forward with having faster websockets. Thanks for connecting me with alex!
