### ISSUE TITLE
ReferenceError: Gun is not defined

### ISSUE THREAD

**Issue by imomin** [amark/gun#263]
Hi,
I saw this project on HN and decided to test it out. I am running following example from "test" folder. https://github.com/amark/gun/tree/master/test/server and I am getting below error.
Any idea why?

```

	Gun.obj.map(queue, function (deferred) {
	^
ReferenceError: Gun is not defined
    at WebSocket.ws.onopen (/../node_modules/gun/gun.js:1426:5)
    at WebSocket.onOpen (/../node_modules/gun/node_modules/ws/lib/WebSocket.js:432:14)
    at emitNone (events.js:86:13)
    at WebSocket.emit (events.js:185:7)
    at WebSocket.establishConnection (/../node_modules/gun/node_modules/ws/lib/WebSocket.js:862:8)
    at ClientRequest.upgrade (/../node_modules/gun/node_modules/ws/lib/WebSocket.js:753:25)
    at ClientRequest.g (events.js:291:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:395:11)
```

**Comment by amark** [comment]
@imomin hey! Thanks for finding this! This is indeed a bug, I'll get it fixed now and published. This bug is specifically effecting server-to-server sync which we're working to add automated tests for but had to build https://github.com/gundb/panic-server first. So I'm glad you caught this for us.

Also, just a quick note though for your sake - That test probably isn't very useful or helpful as an example, so I don't recommend it as a resource for learning or getting started with gun. What are your working on building? Anything I can help out with, or answer to help speed up? Or just browsing and trying to learn stuff - what aspects are you the most interested in, the algorithms or other stuff?

**Comment by imomin** [comment]
I am trying to create server-to-server messaging based on events, something like PubSub. I am trying to achieve 1M message exchange in less than 15 seconds. Currently, I am using net.socket.

**Comment by amark** [comment]
@imomin you'll definitely want to start playing around 0.5 branch then, as all the performance testing is happening there (however server-to-server sync is not done yet, @PsychoLlama is finishing it up soon). The performance testing in 0.5 has been purely core though, not sync - but we need tests (and I'm sure they'll churn up a memory leak or something probably), so I would definitely love to see any of them (aka please keep me in the loop and complain about anything). Also, on an internal load balance test we did ago for a storage engine ( https://www.youtube.com/watch?v=x_WqBuEA7s8 , https://www.youtube.com/watch?v=x_WqBuEA7s8 ) we were only getting 4K writes/sec with Level, which is a start but no where close yet.

Just finished the fix, and pulling/merging/publishing now (but Travis takes a while sometimes).

**Comment by amark** [comment]
oh, clarification @imomin that is disk level writes, maybe the 1M in 15 seconds is latency throughput, not disk?

**Comment by imomin** [comment]
Right, not disk.

**Comment by amark** [comment]
oops, @imomin  I did not mean to close it, however https://github.com/amark/gun/pull/264 does resolve this issue, I am publishing to NPM now. (so I am going to ahead and leave this closed. Thank you for finding this! It caught a bug on a hot patch fix that just came in the other week.)
