### ISSUE TITLE
`map().val()` subscribes while it shouldn't

### ISSUE THREAD

**Issue by Stefdv** [amark/gun#319]
According to @amark `val()` should not subscribe. When used after `map()`  ( which DOES subscribe )  it should even cancel the subscription.
However...
```
var TestCase = gun.get('TESTS');
var test1 = gun.get('test1').put({subject:'test1'})
var test2 = gun.get('test2').put({subject:'test2'})
TestCase.set(test1);
TestCase.set(test2);
TestCase.map().val(function(test){
 console.log('?',test.subject)
});

//  ? test1
// ? test2
```
Let's change a property of one of the tests
```
test2.put({subject:"No don't trigger"});
// nothing is triggered
```
Good so far.Let's add another test
```
TestCase.set(gun.get('test3').put({subject:'test3'}))
// ? test3
```
It shouldn't be triggered!

**Comment by amark** [comment]
Oh @Stefdv , now that you've explained it this does look like correct behavior.

`gun.get('list').map().val(cb)` should get called once for each item in the list, even as they are added. Which looks like what is happening with `test3` (since it is newly inserted) but test2 is properly not getting called with updates.

To get the behavior of "get the list once, and then only each item once" that would be (recently added) this:

`gun.get('list').val().map().val(cb)`

Or if you want to "get the list once, and subscribe to each item" it would be this:

`gun.get('list').val().map().on(cb)`

The different combinations allow you to have very powerful and slightly different uses, all composed based on the chain.

Since this is the correct behavior, I'm gonna close. If I happened to miss something (?) let me know, and feel free to reopen.

**Comment by Stefdv** [comment]
Agreed upon closing...Just not familiair with the new API then ;p
