### ISSUE TITLE
Add integration with Meteor

### ISSUE THREAD

**Issue by vlasky** [amark/gun#325]
Hiyas,

Gun looks like a perfect fit for the [Meteor full-stack isomorphic framework](https://guide.meteor.com/), which is designed for low-latency, real-time web applications.

Meteor natively uses websockets for client-server communications.

Out of the box, Meteor has a pub/sub model in which full-stack apps run MongoDB on the server-side and minimongo on the client within the browser and these are [automatically kept in sync](https://www.discovermeteor.com/blog/understanding-meteor-publications-and-subscriptions/).

With gun, it would be an instance of gun on the server-side kept in sync with gun on the client-side.

I was interested in attempting to try integrating it myself, but at the moment I don't have a clear idea on the appropriate way to replace/override gun's existing websocket code.

**Comment by amark** [comment]
@vlasky help me out here in understanding the use, because gun and meteor compete pretty directly (Meteor is a framework that does everything you could want, while gun is a tiny library that does one thing well).

Certainly, gun might be a good fit for Meteor if they now allow swapping out MongoDB with something else? So then people could have gun powered meteor rather than MongoDB powered meteor?

Here is a simple example of a server side websocket driver for gun: https://github.com/amark/gun/blob/master/lib/uws.js it isn't that hard to swap.

However, it sounds like you are wanting to use Meteor to keep server/client gun in sync? You know that gun keeps itself in sync already between server/client (I don't mean "websocket" sync, I mean actual data sync, state sync, convergence, etc.), right - so what would the goal be then?

**Comment by amark** [comment]
Hey, haven't heard anything further on this. And because I don't understand / it doesn't make sense for this, I'm gonna close this. However if I am not-understanding correctly, let me know and we can re-open it.
