### ISSUE TITLE
Reduce size of gun on npm

### ISSUE THREAD

**Issue by styfle** [amark/gun#327]
I was a bit surprised to see that gun and it's dependencies are 18.8 MB after npm install.

```sh
npm install --save gun
```

![image](https://cloud.githubusercontent.com/assets/229881/23477484/0c23f0c6-fe8c-11e6-8124-4c150fcd44a2.png)

Some ideas on how to reduce the size:

1. Add a `.npmignore` file, see [docs](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package). This could exclude folders such as `test`, `examples`, and anything that is not necessary for gun to work at runtime.
2. Remove the dependency on `aws-sdk` and allow the user to pass in the sdk they wish to use in a Gun constructor. This will reduce the size drastically. By creating a common interface for reads/writes, this would allow the end user to pick which cloud service they want to store the data: AWS, Google Cloud Storage, etc.

**Comment by amark** [comment]
Yesss!!! I've been annoyed by this too. To be honest, you are right, all the dependencies are not necessary to gun "core" they are just "convenient" so gun works out of the box (nobody wants to manually have to "hook" a websocket server up to gun) and S3 and junk.

By itself, gun core is 12KB gzipped and minified! So all this extra junk annoys me.

My recent though would be to have a pre-run script that happens before `npm start` that just checks to see if it needs to install a websocket server or not and does that automatically. So that way things still work/run out of the box by default, but doesn't burden things down. What happens in edge cases though? :/

But yeah, I've always wondered why the NPM package has become so bloated.

**Comment by styfle** [comment]
> My recent though would be to have a pre-run script that happens before npm start

What is wrong with making the "getting started" code include a couple extra lines to wire it up?
This is roughly how I envision it:

```js
const port = 80;
var express = require('express');
var Gun = require('gun');
var AWS = require('aws-sdk');
var app = express();

var myConfig = new AWS.Config({
	credentials: myCredentials,
	region: 'us-west-2'
});

var gun = Gun({
	file: 'data.json',
	aws: {
		config: myConfig,
		bucket: myBucket
	}
});

gun.wsp(app);
app.use(express.static(__dirname)).listen(port);
```

Now there is no dependency on aws but the user can provide it in the constructor. Gun will just have to know which APIs to call in the aws-sdk.

An even better implementation is to provide only an interface to read/write data that Gun requires. Something like the following:

```js
var gun = Gun({
	file: 'data.json',
	cloud: {
		read: aws.s3.readBytes,
		write: aws.s3.writeBytes
	}
});
```

Then the user could wire up any cloud storage.

**Comment by amark** [comment]
@styfle there is nothing wrong/bad with that, and that is ideally more pure and is ultimately at the end of the day what people WILL be doing when they are more complicated configuration. The only reason that isn't the default out of the box is because part of gun's massive growth (53% monthly!!) is because gun, out of the box, just works. So I want to figure out how to automate it without depending upon it (the websocket server is more essential than S3, S3 could probably be dropped without much of a problem now anyways).

**Comment by amark** [comment]
Hey, you're probably seeing the trend I'm trying to keep up with keeping gun core GitHub issues for known bugs/vulnerabilities/current-documentation-flaws. Can we move this over to https://github.com/gundb/feature-requests/issues ? I'm very sensitive to bloat myself, so I'm still very much in favor on reducing things.

**Comment by styfle** [comment]
https://github.com/gundb/feature-requests/issues/23
