### ISSUE TITLE
Pagination and Query

### ISSUE THREAD

**Issue by kethan** [amark/gun#335]
How to Paginate, sort, limit, etc?

**Comment by amark** [comment]
@kethan we actually have an interactive explainer article on this!

Sorting should be done like this: http://gun.js.org/explainers/basketball/basketball.html

Pagination is designed for, but not implemented yet. :(

Limit can be done client side.

In the future, we hope to have a SQL query extension that works like more traditional querying.

What are you planning on building? :)

**Comment by kethan** [comment]
Hi Mark,

Thank you for replying i am trying yo build paas like architecture similar to firebase or parse.
Eg: Firebase has 
query = namesRef.orderByKey().limitToFirst(pageLength).startAt(key);


Regards,
Kethan

**Comment by amark** [comment]
@kethan that sounds awesome! Just FYI gun only loads the data that you request, so it is highly efficient and bandwidth optimized. The only time that you'd need some sort of pagination is if you have really really large tables.

So I recommend trying to build out your system first, and hopefully by the time you are done we'll have the implementation ready. :)

Since this isn't a bug in gun core, but still a worthwhile (and planned-for-the-future) feature, I'm gonna ask we move this to https://github.com/gundb/feature-requests/issues and continue discussion on the https://gitter.im/amark/gun .

Especially on the chat room, people are very helpful in guiding people along in whatever it is they want to accomplish. :D

**Comment by kethan** [comment]
Yeah mark you can move to feature requests.. But my system core is already in place.. So i need the data layer i was thinking of MongoDB then PouchDB now GunDB looks so promising.. If at least i get the idea how to do it... that would be so helpful.
