### ISSUE TITLE
connect to tutorial from a separate tab/browser/device

### ISSUE THREAD

**Issue by dominictarr** [amark/gun#34]
it would make for a more convincing demo if you could open the tutorial in another tab/browser/device and see it syncing in real time.

I see a link to gun.herokuapp.com but it doesn't look like what I was looking at on the gundb.io page.

Is there a simple way to open what I see in a new tab?

**Comment by amark** [comment]
Hey Dominic :) thanks for the retweet.

The actual page that is loaded in the "tabs" is: https://dl.dropboxusercontent.com/u/4374976/gun/web/tabs.html?key=random/sdcws4mU0

Where you replace the key query param with whatever key you got from the tutorial. Load this on different devices/browsers.

Obviously, I should have made this visible in the tutorial itself. But :P I didn't want people knowing I was hosting everything off of the static public folder in Dropbox and 1 freebie heroku box (well this one was obvious) - phew, I'm glad I survived all the traffic without needing any "real" server, part of the sneaky perks of gun.

Your issue is duly noted, though, sir. I should use github pages or something to have nice URLs without masking, and when I do I'll have the tutorial "tabs" URL match their actual iframe.

:) I'm at Stanford right now temporarily, if you're in SF this month we should hang out. But I bet you are already in some other country. ;)

Keep it up (what type of queries were you doing on scuttlebutt?), blessings!

**Comment by dominictarr** [comment]
@amark I'm home in New Zealand right now!!!
Yeah, I am currently hacking on queries...
this: https://github.com/dominictarr/mynosql
at the moment it looks like sql, except only WHERE clauses.
joins will be next, and thinking about how to do some graph stuff.

There are other interesting things too, like, of course since mynosql can have json (including arrays, etc) then can have many-many joins without a join table, etc...

**Comment by amark** [comment]
given my previous comment I'm gonna go ahead and close this. Although @dominictarr we should catch up sometime soon!

**Comment by dominictarr** [comment]
I might maybe be back in US west coast next northsummer. what are you up to?

**Comment by amark** [comment]
Sweet. Was just in Europe/Scandinavia a ton in the fall, bummed I'm not gonna do arcticJS though. Had a kid! :D and now getting 0.3 of gun out the door with 10x performance improvements!

What's your main project now?
