### ISSUE TITLE
single source of truth demo

### ISSUE THREAD

**Issue by coderofsalvation** [amark/gun#342]
Totally awesome project.
Anyone has a setup / repo which demos a website where the content is served from gun.js, and only certain users can edit the content?

I too, just like the author, have dreamed about not having to worry about databases/devops anymore.
However, I can't think of a way to disable editing data when the data is located at the endusers.

**Comment by ctrlplusb** [comment]
There is some related discussion here on #337

**Comment by amark** [comment]
@coderofsalvation have you watched the security series explaining P2P auth? You'll probably find it really interesting since it helps save devops/maintenance cost: http://gun.js.org/explainers/data/security.html

**Comment by amark** [comment]
I do agree that it would be nice to have a demo like this out there, but per my comment on #337 about wanting to keep gun core GitHub issues to actual bugs, I'm gonna ask we move this conversation over to the https://gitter.im/amark/gun or some place like https://github.com/gundb/feature-requests/issues .

People are going to get a whole lot more interaction/discussion on the gitter (which lots of people are in) than issues, so I'm wanting to facilitate people towards the community, since the community is better than the project itself!

**Comment by ctrlplusb** [comment]
+1 to a feature-requests repo.  Things go into a bit of a void via gitter.  So much chatter there.

**Comment by amark** [comment]
Yeah, agreed. That feature-request repo is already up, and doing "+1" or whatever would be a great way to vote on priority too.
