### ISSUE TITLE
Duplicating nodes on S3

### ISSUE THREAD

**Issue by speier** [amark/gun#36]
I'm not sure what is the expected behaviour, but when I call `gun.set` multiple times with the same key, old nodes remains on S3. Basically I have one key object on S3 (for example: `my/first/data`) with correct/updated metadata, but in the `_/nodes/` folder I have old objects (with old souls). Please let me know your thoughts. Thanks.

**Comment by amark** [comment]
Per the sync protocol being based on immutable data, gun core is not allowed to delete data (only null it out). And because gun is fault tolerant, you can only successfully actually delete data if you purge the data from every peer and every storage layer. It is recommended that you just "forget" (de-reference) nodes, rather than delete them.

If you do something like `var foo = gun.set({foo: 'bar'}).key('foo');` and then later do `foo.set({yay: 'pancakes'});` these updates merge as [partials](https://github.com/amark/gun/wiki/Partials-and-Circular-References). GUN should not be duplicating that node, because its soul is what it is actually identified by.

If you mean something like `gun.set({foo: 'bar'}).key('foo');` and then later "gun.set({something: 'else}).key('foo');` then you're just overwriting the key to point to a new node.

However, I don't feel like I understand your question? Could you show an example of what you are talking about? And what you thought was the suppose to be the results?

**Comment by speier** [comment]
This: "It is recommended that you just "forget" (de-reference) nodes, rather than delete them." answered my question. Thank you!

**Comment by amark** [comment]
:) I'd rather have people asking questions than... people not asking at all.
