### ISSUE TITLE
Only publish gun itself on npmjs?

### ISSUE THREAD

**Issue by victornoel** [amark/gun#367]
Hi,

It seems that the whole repository, with example and development libraries are included in the published package on npmjs.

Wouldn't it make sense to restrict it to gun itself as well as the server libs?

**Comment by amark** [comment]
Right now the way I tell people to get started with gun is to `npm install gun && cd node_modules/gun` because this is significantly easier to do on Windows (the nodejs installer is pretty good) than trying to configure git. (Although their new subsystem make make this easier now).

I would like to reduce how long/bandwidth it takes to install gun though - but I think this is more related to AWS-SDK and other dependencies that are bundled, not the couple KB of examples. There is already a discussion on this over here: https://github.com/gundb/feature-requests/issues/23 . (If possible I'd like to merge this discussion with that one, so please continue the chat there, and then I'll close this thread)

Other than saving bandwidth/load-time (which are important to me), what other benefits were you thinking it would have? Contrasted to then the loss of easily-getting-started-examples? (please reply in the other thread, would much appreciate it, thanks!)

**Comment by victornoel** [comment]
ok, good, sorry I forgot about `gundb/feature-requests` :)
