### ISSUE TITLE
NativeScript

### ISSUE THREAD

**Issue by pipeserrano** [amark/gun#391]
How can I use it in a NativeScript project?

**Comment by amark** [comment]
@pipeserrano you should be able to, but I have no experience with NativeScript. Best bet right now is to jump on the https://gitter.im/amark/gun and ask various people to see if they have any experience and/or could help (note: because this is not a bug in gun, I'll probably be closing it as an issue, because as our v1.0 release is coming up I want issues to focus on known-problems people might experience in gun, and encourage people to open up feature request issues over here: https://github.com/gundb/feature-requests/issues ).

@staltz any chance I can get you to submit a PR to `examples/react-native/` with a seed project based on your app you got working? (Any problems so far? Let me know so I can get them fixed. How is it going?)

**Comment by amark** [comment]
thanks for opening it up over there! Gonna close this one now. For everybody else, continue the discussion there: https://github.com/gundb/feature-requests/issues/26 .
