### ISSUE TITLE
MQTT support for IoT

### ISSUE THREAD

**Issue by buckle2000** [amark/gun#430]
Just FYI:
Seriously. The embeded offline support is not enough for IoT.
If gundb can connect directly to a MQTT broker, then IoT device will be able to use gundb.

**Comment by d3x0r** [comment]
others have been using gun on RPi's using just the standard websockets... 
It wouldn't be very hard to develop a plugin that could support this sort of thing... for an example that does that ... 

https://github.com/d3x0r/gun-ws

https://github.com/d3x0r/gun-ws/blob/master/gunws.js  a whopping 88 lines.

**Comment by amark** [comment]
@buckle2000 we'd love it if you'd contribute those 88 lines like @d3x0r mentioned! As we don't have any experience with MQTT libraries. This would be an awesome feature! :D Let us know!

Since this would be a feature addition, and we're trying to keep the github issues stuck on important bug fixes needed for the upcoming v1.0 release, we're asking that all feature requests be added here instead: https://github.com/gundb/feature-requests/issues . So gonna close this issue here for now.
