### ISSUE TITLE
sea.js not blocking data tampering?

### ISSUE THREAD

**Issue by zanetu** [amark/gun#439]
Please see comments inline. 

```
<html>
    <body>
        <script src="gun_v20171016.js"></script>
        <script src="cryptomodules_v20170919.js"></script>
        <script src="sea_v20171016.js"></script>
        <script>
            localStorage.clear()
            var gun = Gun(), user = gun.user()
            user.create('alice', 'password1', function(ack) {
                user.auth('alice', 'password1', function(ack) {
                    var aliceKey = 'pub/' + ack.pub
                    gun.get(aliceKey).put({hello: 'world'}, function(ack) {
                        gun.get(aliceKey).get('hello').val(function(v) {
                            //actual: world
                            console.log('expected: world; actual:', v.split('"')[1])
                            user.leave(function(ack) {
                                user.create('bob', 'password2', function(ack) {
                                    user.auth('bob', 'password2', function(ack) {
                                        //bob should not be allowed to tamper with alice's data
                                        gun.get(aliceKey).put({hello: 'void'}, function(ack) {
                                            gun.get(aliceKey).get('hello').val(function(v) {
                                                //actual: void (bug?)
                                                console.log('expected: world; actual:', v.split('"')[1])
                                            })
                                        })
                                    })
                                })
                            })
                        })
                    })
                })
            })
        </script>
    </body>
</html>

```
Let me know if I am using GUN or SEA in a wrong way.

**Comment by amark** [comment]
@zanetu you are doing this correctly. This is GUN behaving incorrectly, not SEA - which I was fixing gun last night. Combining SEA + GUN is very alpha right now, and I'm super happy you are here already testing and building things! Very much appreciated.

SEA **should** be entirely invisible, so the fact that you are seeing `SEA[]` as your `v` value means that things aren't working. Here is why:

SEA's signature verification is asynchronous, yet GUN is reacting synchronously. As a result, two things happen:

 1. GUN fires your callback **before** SEA has "unwrapped" and verified the data.
 2. GUN fires your callback before it is told the data is invalid and should be rejected.

I have some changes already that almost have this fixed. What it does is:

It switches GUN internally to depend on the async middleware that SEA is calling.

**Comment by zanetu** [comment]
@amark 
Thanks for the explanation. Actually I have a lot more questions to ask about design specs and use cases of GUN+SEA. If you wish, I could submit an issue titled "GUN+SEA wishlist" to github.com/gundb/feature-requests and update it ocassionally with my thoughts and doubts on GUN+SEA. If not, I'll wait until you implement/fix basic features (When?) and/or come up with a more detailed API along with simple examples, probably at https://github.com/amark/gun/wiki/Auth.

**Comment by amark** [comment]
@zanetu I meant to reply here after I published v0. 8.8, I used a variant of your code as a test (you can run it after you install devdepedencies by doing `mocha test/panic/users.js`). So this is fixed now!!! :) let me know if you need anything, thanks for reporting this!!! Please report anything else.

**Comment by zanetu** [comment]
I did not run your test with mocha but when I opened my html file which uses the latest `/test/sea.js` I got the following error:
```
sea_v20171021_test.js:28 Uncaught ReferenceError: require is not defined
    at sea_v20171021_test.js:28
```
It appears that `/test/sea.js` is not working correctly with a browser. 

When I used the latest `/sea.js`, which differs a lot from `/test/sea.js` (Why two different `sea.js` files, by the way?), I got no output at all. It seems the callback function of `user.auth()` is never executed. (See inline comment below.)
```
<html><body>
<script src="gun_v20171021.js"></script>
<script src="cryptomodules_v20170919.js"></script>
<script src="sea_v20171021.js"></script>
<script>

localStorage.clear()
var gun = Gun(), user = gun.user()
user.create('alice', 'password1', function(ack) {
	user.auth('alice', 'password1', function(ack) {
		//never called
		console.log('This is never printed.')
	})
})

</script>
</body></html>
```

**Comment by amark** [comment]
@zanetu it appears that `window.crypto.subtle` is only available on pages that are either `https://`, `file://`, or `localhost` which is super annoying.

Here is your example working on codepen: https://codepen.io/anon/pen/PJvYxP?editors=1012 (wait a few seconds), however I had a couple problems myself:

1. It appears a `auth(` immediately following a `create(` does not work, however it **does work** if I put a `setTimeout` to make it async. I'll push a temporary fix for this to the master branch.

2. `user.leave` seems to have problems. So please avoid using it. (If you need to use it, have the browser refresh/reload rather than logging out).

3. I needed to refire `gun.user()` again to "clean things up".

Sorry about that. You are very  much on the bleeding edge of SEA. So there are lots of little quirks like that. I'll push some temporary fixes to the above for now. But hopefully this will let you get rolling. What are you trying to build, again?

**Comment by amark** [comment]
Got (1 ~ 3) working, here: https://codepen.io/anon/pen/xXNxdo?editors=1112

**Comment by zanetu** [comment]
@amark

Thanks a lot for your prompt response. 

I tried your latest fix on my local html and it worked correctly, except for a 10s delay before the 2nd "expected: world; actual: world" was printed. 

Among others, I am thinking of building a simple scoring system, as is exemplified below. 

```
'books': {
	'ISBN-0553380168': {
		'title': 'A Brief History of Time',
		//scores range from 1 to 10
		'scores': {
			'<Alice's Public Key>': 9,
			'<Bob's Public Key>': 7,
		},
	},
}
```
However, I have some doubts/suggestions regarding the design of GUN+SEA. 
1. It seems only the pattern `pub/<A Public Key>` at the root level is accepted. I tried, respectively, changing `var gun = Gun()` to `var gun = Gun().get('l1')`, and changing `var aliceKey = 'pub/' + ack.pub` to `var aliceKey = ack.pub`. The last output changed to "expected: world; actual: void" in both cases, which suggests data protection was not in effect. To my mind, this design restricts the scope of possible use cases. 
2. Once a user is allowed to store protected data in any pattern at any level, he/she should be allowed to reject any attempt to hijack, at any level in a JSON structure, a resource that is meant to be public or belong to another user. Consider the `books` examples above. If Bob locally creates `ISBN-0553380168` after logging in, Alice can still create an unprotected `ISBN-0553380168.scores` locally, log in, and put her score into it. When Bob tried syncing `books` with Alice, Alice can reject the protected `ISBN-0553380168` from Bob. (Please ignore this suggestion if GUN+SEA is already immune to this risk at any level in a JSON structure.) 
3. I wonder if GUN+SEA provides a way to export/import a user's public-private key pair, as a user might wish to use the same identity across multiple browsers and devices.

**Comment by amark** [comment]
@zanetu you are correct, all 3 of those are already being addressed (they were actually the disclaimers I made when I announced the update on gitter!).

1. Right now only key/value data on a user account works. Don't worry though, it will not be limited to that. In the future we'll have tests to make sure you can save encrypted documents/graphs/tables to the user account.

2. Yes, this will become available using the future planned `data.trust(user)` API method.

3. From my collaboration with the folks at MIT, it sounded like it will be necessary in the future to support aggregated private key pairs. So that, yes, users can import and reuse their identity. This is honestly a long ways out though. If you helped build it, it could happen sooner though.
