### ISSUE TITLE
Log the Journal

### ISSUE THREAD

**Issue by metasean** [amark/gun#44]
1) Enable journaling of updated objects and properties.

2) Provide application programmer control (API) to turn journaling on/off.

**Comment by metasean** [comment]
1) Enable journaling of updated objects and properties.

2) Provide application programmer control (API) to turn journaling on/off.

**Comment by amark** [comment]
Journaling already exists (it is what happens over the wire).

BUT logging it to a file currently is not available, so adding this option is a high priority.

**Comment by amark** [comment]
Because journaling comes with a lot of extra data storage and additional feature code, we're going to classify this as an "extension" or "plugin" to gun (since it can be built on top of gun) not a "core" behavior. As a result, this can be moved to https://github.com/gundb/feature-requests and I'm gonna close this one.
