### ISSUE TITLE
update wiki page for "Adding Storage Services"?

### ISSUE THREAD

**Issue by zakdances** [amark/gun#444]
On the Adding Storage Services [wiki page](https://github.com/amark/gun/wiki/Adding-Storage-Services), there's a note that says:

> WARNING: This documentation is out of date. We use a different storage adapter system now.

This wiki page contains pretty important information - is it possible to update the page with the current system details or is there some other place to read about how to write custom adapters?

**Comment by sjones6** [comment]
Thanks for bringing this up! This could use a bit of a refresh. 

In the meantime, have you seen gun-flint aka "flint"? https://github.com/sjones6/gun-flint

Flint has pretty good docs on using it to write custom adapters and doesn't require knowledge of guns wire spec. It should be flexible enough also for most use cases.

@zakdances does flint help out with what you're after?

**Comment by amark** [comment]
thanks @sjones6 :)

I updated the page to point to `flint` because flint is legit good.

@zakdances I'm sorry that docs aren't up to date :( I'm unfortunately drowning in stress/work related to gun that I can't get around to these other things.

The wiki is a wiki though, so please anybody is free to update them based on flint or the default/example storage adapters.

Flint is really good though, and has a lot of good docs itself. So I'm gonna close this for now.

**Comment by zakdances** [comment]
@sjones6 Sorry about the late response. I haven't had time to check out Flint yet, but I'll do it as soon as I'm able. Thanks for the recc'd!
