### ISSUE TITLE
Method .open(cb) returns duplicates

### ISSUE THREAD

**Issue by sergibondarenko** [amark/gun#458]
gun 0.8.9, directly from the master branch
```
$ grep gun package.json 
    "gun": "git+https://github.com/amark/gun.git#master",
```

Code:
```
const moment = require('moment');
const Gun = require('gun');
require('gun/lib/path');
require('gun/lib/open');

let counter = 0;
const interval = 5000;

const gun = new Gun({peers: ['http://localhost:8080/gun']}); 
const park = gun.get('jurassic');

setInterval(function () {
  park.path('trex').put({
    name: 'trex' ,
    stat: {
      force: 43,
      speed: 14
    }   
  }, function (ack) {
    if (ack.err) {
      console.log(ack.err);
      return;
    }
    
    console.log('time: ', moment(new Date()));
    console.log('counter: ', counter++);
  
    park.path('trex').open(function (data) {
      console.log('trex data: ', data);
    })
  }); 
}, interval);
```

Expected results:
```
time:  moment("2017-11-14T17:09:03.211")
counter:  0
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }
time:  moment("2017-11-14T17:09:08.210")
counter:  1
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }
time:  moment("2017-11-14T17:09:13.217")
counter:  2
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }
```

The result I get:
```
time:  moment("2017-11-14T17:09:03.211")
counter:  0
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }
time:  moment("2017-11-14T17:09:08.210")
counter:  1
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }
time:  moment("2017-11-14T17:09:13.217")
counter:  2
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }
trex data:  { name: 'trex', stat: { force: 43, speed: 14 } }

```

There is no such problem with `.val(cb)`

---
**UPDATE**

I run this code 636 times and now I have more then 2000 duplicates on my screen.

**Comment by amark** [comment]
Oh boy :P I'll be looking into this.

**Comment by eallik** [comment]
@sergibondarenko you're making an `open` call every iteration, for example if you put `if (counter === 1) { ... }` around `park.path('trex').open(...)`, you won't have any duplicates.

**Comment by amark** [comment]
@eallik you rock! I'm so glad to know this wasn't an issue with `.open` directly. I very much appreciate you jumping in and helping check these issues. Will close!

@sergibondarenko hope you are doing well! How is the project going?

**Comment by amark** [comment]
@eallik spot on insights! Some of my original code would re-use the same function so that yes, all your code was necessarily declarative and FRP. :D :D :D That is the way I'd rather have it...

BUT this proved to be too difficult for people transitioning from a procedural mindset into GUN, and I promised everybody that I wanted GUN to be the "easiest database ever" so :( I decided that **I** was wrong, and rewrote everything.

The original example was calling a `.open` inside a `setInterval` which I think is pretty rare/obvious somebody is going to do that in non-"here is how to replicate the bug" code. So I don't think it merits doing this automatically, although that may be an interesting feature to think about (or its own extension? Wouldn't be too hard, especially if built on top of `open`). Further, for those who do need do stuff in a `setInterval` or similar loop, they can use `.load` which is the same thing as `.open` except only once (aka, procedural. So ever interval performs the action once and is done).
