### ISSUE TITLE
Priority/Sharding Options

### ISSUE THREAD

**Issue by metasean** [amark/gun#46]
Interface for application developers to determine sharding priorities.

Factors that may impact sharding priorities:
- authentication (machine versus user?)
- authorization (machine versus user?)
- query-based
- schema-based

**Comment by metasean** [comment]
#45 is a prerequisite

**Comment by amark** [comment]
This realistically is going to wind up being driver/storage adapter specific (although we could probably standardize/uniform the options for it). Lets migrate this to https://github.com/gundb/feature-requests , and I'm gonna close it here (so people know it isn't a gun "bug" just a feature request - it'll be important for people to differentiate between these).

**Comment by dioptre** [comment]
Hi @amark I can't see this in the docs and wondered what's required to get this working and maybe if I can help.

**Comment by amark** [comment]
Hey @dioptre :) how are you doing?

By chance did you see this article https://github.com/amark/gun/wiki/sharding ?

What are you building?

so storage adapters listen to a `Gun.on('put', cb)` hook, the best way to write a sharding function is to add a `put` listener before the storage drivers add themselves. Then in that middleware function, check the update `ctx.put` and run each UUID through your shard detection function, if they do not pass, reject the update from being stored on this device. Then all you have to do is have different devices have a different "range" of the shard function.

Let me know what you are trying to do, and lets see if we can work something out.

**Comment by dioptre** [comment]
Hey @amark I did see the article - but as much as you don't believe in it - I need it for a use case.

I'm storing personal records on local machines and networks, and want to publish the same into a larger 'borg' system - where it's optional to sync shards selectively - based on user auth and group key exchange as what you call true security.

Not sure if this is the right way to go about it. I'll be wanting to use gun as mostly metadata and instead will store/stream/sync/crypt files along with into s3 up to the terabytes. I was thinking of setting up a storage backend to replace gun's s3 too - I prefer Cassandra, and have been looking at JunoDB.

**Comment by amark** [comment]
@dioptre ah, yes. You'd be using security/auth to determine your shard function? That sounds like a good way to go. I'll be publishing an example of auth-enabled P2P crypto social network in the next couple of weeks, too! So be on the watch out for that :).

So yes, this is possible - those event hooks I mentioned give you pretty unlimited control over behavior - although it would be good to understand gun's control flow first though.

I haven't heard of JunoDB before? Couldn't find any links either?

**Comment by dioptre** [comment]
It's the successor to Titan - might venture to say it might be the future
of graph databases as far as I can see.

Thanks for the heads up!

Regarding the ws-service write back - any tips on how to limit
subscriptions to shards too? ;)

On Fri, Mar 24, 2017, 19:48 Mark Nadal <notifications@github.com> wrote:

@dioptre <https://github.com/dioptre> ah, yes. You'd be using security/auth
to determine your shard function? That sounds like a good way to go. I'll
be publishing an example of auth-enabled P2P crypto social network in the
next couple of weeks, too! So be on the watch out for that :).

So yes, this is possible - those event hooks I mentioned give you pretty
unlimited control over behavior - although it would be good to understand
gun's control flow first though.

I haven't heard of JunoDB before? Couldn't find any links either?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/amark/gun/issues/46#issuecomment-289112253>, or mute
the thread

**Comment by amark** [comment]
@dioptre you don't need to use gun's built in socket adapters - they're small/short ~100LOC. You can wrap it yourself (all you need to do is call `gun.on('in', msg)` with the payload and handle outgoing messages as you like), which if you do would let you firewall as necessary.

Ah, I know Titan... still can't find any links of anything related to it called Juno. Have anything to share?

**Comment by dioptre** [comment]
Sh#$t was a mobile typo:

https://github.com/JanusGraph/janusgraph
