### ISSUE TITLE
Used ws version ( 3.3.3 ) causes connection issues in Chrome

### ISSUE THREAD

**Issue by Stefdv** [amark/gun#472]
If using ws v3.3.3 Chrome (Windows 10 ) crashes on page reload. Downgrading ws to version 3.3.2 solves this.
tx to Toni @funkizer

**Comment by Stefdv** [comment]
Hmm...No, it does NOT solve it. Now the web page can't connect...wich is probably the reason the server doesn't crash

**Comment by Stefdv** [comment]
https://github.com/websockets/ws/issues/1256
<quote>
Issue is caused by lack of error listener on the socket, and can be fixed like so:

ws.on('error', () => console.log('errored'));
This isn't documented in the README.md, and seems to be a pretty big breaking change.

**Comment by Stefdv** [comment]
Hmm... it seems you already covered that... 
Strange things happen... cleaned out my whole node_modules folder, deleted my `package-lock.json` and installed everything again...problem solved.
Closing the issue

**Comment by nalbina** [comment]
I recently had a lot of trouble with this. in the gitter chat, we discussed that ws `v3.3.2` was the issue. 
cc @zrrrzzt

**Comment by dfreire** [comment]
Well, I'm having this precise problem right now with Chrome/OSX.
I tried deleting 'node-modules' and 'package-lock.json' and reinstall everything...
Still doesn't work...

In Firefox everything looks ok, though.

**Comment by zrrrzzt** [comment]
I think this is fixed, but not released yet.
As a temporary quick fix you can add `ws: 3.3.2` to your dependencies in `package.json`

**Comment by dfreire** [comment]
Yeah, that works for me. Thanks @zrrrzzt :-)

**Comment by amark** [comment]
Gonna leave this open until I publish the fix then will close, sorry it is taking longer than I thought! Maybe I'll just wind up publishing it as its own release... give me a few days.

**Comment by amark** [comment]
This should be officially fixed in `0.9.7` via https://github.com/amark/gun/blob/master/lib/ws.js#L38

Thanks to @d3x0r @Stefdv @nalbina @dfreire and others.

I deeply apologize about this version mix up with WS...

On one hand, it angers me greatly that a change in WS caused a **terrible** experience for several people who reported it (and I have no clue how many people experienced but didn't report it)...

And on the other hand, I'm upset with myself that my NPM packages happened to be conveniently different than everybody else, I should have done a fresh install.

Closing!
