### ISSUE TITLE
Can't use sea within a nodejs application

### ISSUE THREAD

**Issue by nalbina** [amark/gun#478]
using `create-react-app` I have a nodejs application. In there I `npm install -S gun` and therefore import gun into the project with 
`import Gun from 'gun/gun'` and sea with `import User from 'gun/sea'`
This doesn't work out of the box and prompts for other modules to be installed, namely

- "atsign trust/webcrypto"
- fake-indexdb 
- node-webcrypto-ossl
- spark-md5

I'm not sure if this is the right way anyways since sea enhances gun in a way so I wouldn't do anything with `User` as I imported it above?

Also, when I have completed the installation of the extra packages, I am getting this error which is probably coming from eslint and stops me from going forward.

```
./node_modules/gun/sea.js
52:23-30 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/@trust/webcrypto/src/algorithms/SupportedAlgorithms.js
84:22-60 Critical dependency: the request of a dependency is an expression
```

**Comment by nalbina** [comment]
Spend a bit more time digging:

```
sessionStorage = new require('node-localstorage').LocalStorage('.sessionStorage');
localStorage = new require('node-localstorage').LocalStorage('.localStorage');
```
my nodejs application explodes on these lines so I altered them to do
```
sessionStorageR = require("node-localstorage")
var sessionStorage = new LocalStorage(
  ".sessionStorage"
);
localStorage = new LocalStorage(".localStorage");
```
now it 'only' explodes for the second error, and on top of that I get an error:`fs.existsSync is not a function` which is coming from `node-webcrypto-ossl/buildjs/key_storage.js:49` 
I will report back once i get some progress.

**Comment by woudsma** [comment]
I'm also trying to use SEA in a `create-react-app` with `react-scripts@^2.0.0-next`, but no luck so far. 
The `sea.js` file uses the ES7 object rest spread operator in `sea/secret.js` on lines 13-37.
To compile i would require the `@babel/plugin-proposal-object-rest-spread` babel plugin,  which i cannot use without ejecting my React app - i don't want to do that. So i tried to manually convert the `sea.js` file to ES5, but now i'm stuck on this error:
```
sea.js:331 Uncaught ReferenceError: regeneratorRuntime is not defined
```

**Comment by amark** [comment]
@woudsma I would **LOVE** an ES5 version of SEA! I don't like all the ES6 complexity.

Do you by chance have a PR of your conversion, that I could look at, and perhaps pick up/pull and help you work around whatever quirks you are having?

The error you got is very odd, `regeneratorRuntime` does not exist in GUN or SEA codebase, so it must be coming from a NodeJS WebCrypto wrapper shim polyfill. How to replicate error?

**Comment by amark** [comment]
@nalbina just as an update since the original December post, my recent (less than a month ago?) refactor cleaned up a lot of unnecessary dependencies (like `ossl` and `localStorage` in NodeJS).

While this is an improvement, some Crypto functions aren't available with the "cleanup" and if called, still break. But at least this is some slow improvement, especially if @woudsma has some ES5 cleanups of the spread operators.

At least we're able to make a bunch of changes while SEA is in alpha, so please feel free to contribute!

**Comment by femanso** [comment]
I had this exact same problem, but with vue-gun, since I hadn't much time to investigate, what I did is:
```
npx babel node_modules/gun/sea.js --out-file server/gun/sea.js --presets=env,stage-2
```

and then imported manually on ~/plugins/gun.js
```js
import Vue from 'vue'
import VueGun from 'vue-gun'
import Gun from 'gun'
import './sea.js'

Vue.use(VueGun, {
  gun: Gun()
})
```
I also have updated node and npm and babel-cli to the latest stable versions

not the perfect world, but it's working, I think manually loading the compiled file would work for react too

**Comment by amark** [comment]
@nalbina @woudsma @femanso thanks to @zer09 's PR from a bit ago, the way that SEA in NodeJS depends upon external crypto libraries has been significantly improved. And should no longer be crashing.

@robertheessels did a great job switching a lot of `...` to ES5. I'd like to continue the ES5 port, but it is low priority since this shims WebCrypto which requires more modern browsers anyways (I'm an ES5 pundit and evangelist, so this is hard for me to admit!).

Going to close, although I'm sure there may be more/other issues with SEA and NodeJS, so please feel free to reopen.

**Comment by u007** [comment]
im using this on my react project with vite-ssr-plugin
```
import GUN from 'gun/gun';
import SEA from 'gun/sea';
```
