### ISSUE TITLE
How to do pagination in gun?

### ISSUE THREAD

**Issue by qwe123wsx** [amark/gun#479]
I need something like gun.get({startkey, endkey})

**Comment by sebastianmacias** [comment]
I have the same need as well.

**Comment by amark** [comment]
@qwe123wsx @sebastianmacias apologies for the delay!

The **wire spec** has a protocol for this but it isn't implemented yet. It looks something like this:

```
gun.on('out', {get: {'#': {'>': 'a', '<': 'b'}}});
```

However this doesn't work yet. I would recommend instead:

(1) Pagination behavior is **very different** from one app to another and will be hard for us to create a "one-size-fits-all" solution, so it would be highly helpful if you could implement your own* pagination and make it available as a user-module, then we can learn from your experience (what worked, what didn't) and make the best solution part of core.

(2) Your app will probably work fine without pagination in the meanwhile, while it can be built (it is targeted for after 1.0), and then as your app becomes more popular, it should be fairly easy to add in without much refactor, once you need it and it is available.

* How to build your own?

Lots of good articles on this, best one I've seen yet is from Neo4j on how to do it in a graph database (which applies to gun as well) https://graphaware.com/neo4j/2014/08/20/graphaware-neo4j-timetree.html .

Another rough idea is you model your data based on pagination or time. So rather than having ALL tweets go into user's tweet table, instead, the user's tweet table is a table of DAYS (or weeks), and then you put the tweet inside the week table. Now when you load the data, you can scan/skip based off of week very easily while it being super bandwidth efficient.

Rough PSEUDO code:

```
function onTweetSend(tweet){
  gun.get('user').get('alice').get('tweets').get(Date.uniqueYear() + Date.uniqueWeek()).set(tweet)
}

function paginateUserTweet(howMany, cb){
  var range = convertToArrayOfUniqueWeekNamesFromToday(howMany);
  var all = [];
  range.forEach(function(week){
    gun.get('user').get('alice').get('tweets').get(week).load(function(tweets){
       all.push(tweets);
       if(all.length < range.length){ return }
       all = flattenArray(all);
       cb(all);
    });
  });
}
```

**Comment by amark** [comment]
question ported to StackOverflow: https://stackoverflow.com/questions/48953233/how-do-you-do-pagination-in-gun/48953254#48953254

Closing this issue, since it isn't a bug. :)
