### ISSUE TITLE
Auth in a React environment

### ISSUE THREAD

**Issue by andrycodestuffs** [amark/gun#480]
> To get started building your app, just include SEA in your app:
> ```javascript
> <script src="https://cdn.jsdelivr.net/npm/gun/gun.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/gun/lib/cryptomodules.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/gun/sea.js"></script>
> ```
> Now in your javascript you can instantiate gun and and reference your user:
> ```javascript
> var gun = Gun();
> var user = gun.user();
> ```

My react environment uses webpack, how do I access gun.user from the example without using CDNs or global Gun variable?

**Comment by amark** [comment]
@andrycodestuffs I do not use React, but I do know that React/webpack **is compatible** with CDNs/script-tags/etc. so you should be able to mix the two without a problem.

There is a solution with only React and Webpack, but I'm not the expert (maybe somebody in the chat room https://gitter.im/amark/gun can help, several use React). Will close this soon as it isn't a bug, but I definitely want to get it sorted out / documented!

**Comment by TheHollidayInn** [comment]
For me, I put gun in the base index.html and use the global Gun variable. There are a few other libraries I've had to do this with as well. If there is a different solution, I'd love.to see.

**Comment by andrycodestuffs** [comment]
I think that the user object should be available by default or maybe using Gun()'s options object.
In a webpack environment you would prefer having everything bundled in your node_modules rather than using script tags.
I'll maybe work on it and later release a pull request

**Comment by amark** [comment]
@andrycodestuffs I appreciate that! If you figure out how to get it working, please submit a PR for the bundle (although please don't submit a PR for adding webpack as a dependency, I'm trying to avoid that), but would love the bundle!

You are right, the `user` method is very useful and most people are going to wind up including it - so why not have it by default? Unfortunately, a couple reasons:

1) SEA is in alpha right now and likely buggy.

2) SEA is almost as large as GUN!!!

3) SEA depends upon an enormous amount of bleeding-edge browser features (like the Web Crypto API) and would instantly crash even modern browsers that don't have those features yet.

As a result, we'll be leaving it up to including it separately (our goal is to eliminate the need for `cryptomodules` entirely) and/or bundle it, **certainly** bundling it needs to be easier / well-documented. Would love to have your contributions on this, as IDK how webpack/etc. work.

Gonna close since I'm trying to keep core issues to v1.0 stability concerns. But I do agree, this does need to be documented / made-easier!

**Comment by andrycodestuffs** [comment]
@amark I fully agree with you.
I discovered GUN.js recently and I think that webpack integration is difficult now but of course it could be improved in the future.

I'm currently working on a project but I'd love to collaborate!

**Comment by amark** [comment]
@andrycodestuffs awesome :D let me know, and hop into the chat room when you have time - everybody is super friendly there!
