### ISSUE TITLE
HDFS as S3 Alternative for Storage Engine

### ISSUE THREAD

**Issue by metasean** [amark/gun#50]
Explore Hadoop HDFS as a storage option (e.g. alternative to S3)

**Comment by Xe** [comment]
might want to look into elasticsearch too

**Comment by amark** [comment]
@Xe , yes! BTW what ever happened? We lost contact after I had been flying around, and then you started to fly around. And then I've been too busy to follow up, but now we're moving back into development/documentation mode. You still wanting to do the SQL stuff?

**Comment by amark** [comment]
Clarification on this thread: This is specifically using HDFS as an alternative to S3 or GCS for people running their own physical machines. This is not about using Hadoop as in Hive or MapReduce. Changing issue subject now to reflect this.

**Comment by amark** [comment]
Will need somebody who is smarter than me to write an adapter/driver for gun to this - the other adapter/drivers should be helpful reference points for getting started.

HDFS compatibility won't be an "out of the box" adapter though, so I'd like to close this issue (so that way gun issues are about "bugs" not feature requests) and if still desired (and somebody who can help) can help work on this over in: http://gun.js.org/explainers/data/security.html . https://github.com/gundb/feature-requests . So gonna close here.
