### ISSUE TITLE
Can 2 (or more) browsers communicate as peers even when they are offline ?

### ISSUE THREAD

**Issue by jalchr** [amark/gun#506]
Sorry if this question looks trivial. 
I'm having this question https://stackoverflow.com/questions/48908655/how-can-a-number-of-angular-clients-communicate-between-themselves-even-when-the/48909071?noredirect=1#comment84913140_48909071 

I wonder if gun works offline as a database medium inside the browser... 
I.e. Can 2 browsers communicate even when both are offline ?
if so... any guides would be great.

Many thanks

**Comment by amark** [comment]
@jalchr it'd be appreciated if you could move this (and my answer) into a StackOverflow question tagged with GUN, as it isn't a bug. Here is my reply:

1. Since GUN can connect to multiple peers, you can have the browser connect to both outside/external servers AND peers running on your local area network. All you have to do is `npm install gun` and then `npm start` it on a few machines within your LAN and then hardcode/refresh/update their local IPs in the browser app (perhaps could even use GUN to do that, by storing/syncing a table of local IPs as the update/change)

2. Ideally we would all use WebRTC and have our browsers connect to each other directly. This is possible **however** has a **big problem**, WebRTC depends upon a relay/signal server every time the browser is refreshed. This is kinda stupid and is the browser/WebRTC's fault, not GUN (or other P2P systems). So either way, you'd have to also do (1) either way.

3. If you are on the same computer, in the same browser, in the same browser session, it is possible to relay changes (although I didn't bother to code for this, as it is kinda useless behavior) - it wouldn't work with other machines in your LAN.

Summary: As long as you are running some local peers within your network, and can access them locally, then you can do "offline" (where offline here is referencing external/outside network) sync with GUN.

GUN is also offline-first in that, even if 2 machines are truly disconnected, if they make local edits while they are offline, they will sync properly when the machines eventually come back online/reconnect.

I hope this helps.

**Comment by amark** [comment]
Please copy it for me! On phone and hard to do right now. Thanks :)
