### ISSUE TITLE
How to Set Permissions Required for Setting Data

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [amark/gun#513]
How can I make it so some of the database can only be modified by my server?

**Comment by amark** [comment]
@TimeTravelersHackedMe welcome :) just as a quick tip, you'll get faster *help* if you ask here ( https://gitter.im/amark/gun ) or (more appropriately) use StackOverflow ("gun" tag) for asking questions (in fact, if you could copy your question here AND my answer over to SO it would be greatly appreciated, helps save me a ton of time plus makes the Q visible to others - please just paste my answer). GitHub issues are intended for bug reports.

So in case you don't know already, GUN's architecture is fundamentally P2P/decentralized by design, which means any/all security we are building will also be fully P2P and therefore not based on centralized servers.

If you are curious how that works, we created some super simple 1 minute animated explainer videos that teach the concepts, check them out here: http://gun.js.org/explainers/data/security.html !

Our security framework, SEA (Security, Encryption, Authorization) already enables user-permissioned graphs. Check out http://gun.js.org/docs/Auth for more information.

It currently (but support for it is planned soon) doesn't do shared multi-user objects, but it will soon. Somebody else actually just asked me how it will be implemented, which I answered here: https://gitter.im/amark/gun?at=5a9907d9c3c5f8b90d230498

Finally, if you want centralized (server-only) read/write access, it is possible to build but there is not much community or official support around this. A good starting point is probably https://github.com/zrrrzzt/bullet-catcher which I think does what you want.

Please don't for get to move this to SO for everybody else! Thanks :D cheers! Hope to see you in the chat room! https://gitter.im/amark/gun

**Comment by TimeTravelersHackedMe** [comment]
@amark do you know how I can restrict writing to the database to only a certain user and allow anyone to read the database?

**Comment by amark** [comment]
@TimeTravelersHackedMe http://gun.js.org/docs/Auth shows you how to do that.
