### ISSUE TITLE
Divide client and server

### ISSUE THREAD

**Issue by iBobik** [amark/gun#520]
I see that in our frontend-only project it downloads awssdk only for Gun server.

I propose to divide Gun to thwo packages - gun server and client. They will have most of things shared, but some libraries are needed only on server and frontend clients will not need it.

**Comment by amark** [comment]
@iBobik hey :D welcome :D :D :D !

These two things are already divided correctly as you say. I'm not sure what happened with your project, could you explain?

If you see the main `gun.js` file, the one in the browser/front-end tutorials we show as using via https://cdn.jsdelivr.net/npm/gun/gun.js or (if you are running a server) `http://localhost:8080/gun.js` it will only download gun and browser specific adapters (localStorage, websockets, etc.)

When you use `npm` or `yarn` via the command line, it also downloads some default server tools like adapters and libraries for S3 (thus awssdk, although I eventually want to remove this as a dependency entirely, because it is "optional" not required). This should never show up in the browser/frontend though.

Could you explain what happened?

**Comment by amark** [comment]
(gonna close, since they are already divided, but PLEASE reply so I can try to help you fix whatever happened in your app. Or if something really really really weird is happening, we can re-open it. But I just tested... and it doesn't load awssdk in the browser.)

**Comment by iBobik** [comment]
I see it in packages-lock.json and it is not problem. Just my OCD screams. ;-)

**Comment by amark** [comment]
Oh! Yeah, what is in the package list is different than what gets loaded in the browser. :/ Over time I hope to clean up the package list, but it isn't currently wrong. Sorry about that!
