### ISSUE TITLE
Gun collection design for scalability, security, role permission.

### ISSUE THREAD

**Issue by Devric** [amark/gun#521]
Hi Mark/GunComunity

Just start to look at Gun after some search on Offline First DB. cool stuff here. but not sure if GUN suitable for my need, or if I'm heading the right direction.

A quick clarification of what I'm after.

- User has multiple devices that will sync with each other almost real-time ( GUN 👍 )
- User can collaborate their stuff with other users in real-time (GUN 👍 )
- Can be used offline for downloaded Data or creating new Data (GUN 👍  )

Q1. 
I'm planning to use GUN only for real-time interaction with conflicts management, so I think I would have a "Gun Peer" at the server side for business logic to interact with a more traditional database.  Is there a better approach for a bit more on server-side control than using a Peer.

Q2.
wondering how to design the structure, and how to make the app scalable with this scenario.

- support large user base, maybe owning 200 items per user ( the content of each item might be small roughly 10kb max )
- Each item has a permission level i.e (owner, admin, viewOnly)
- User Bob creates ITEM:ONE owner (private only) 
- User Bob creates ITEM:TWO  ( Alice as Admin, can Edit )
- User Bob creates ITEM:THREE (Shared with User Alice as view only).
- Alice can not view or download ITEM:ONE
- Alice will download and view ITEM:TWO, and ITEM:THREE, to her local storage
- Alice will able to make an update to ITEM:TWO

Do I keep every user's data in a single Gun server instance? Gun will smart enough to download the needed object for a particular user? ( described in https://github.com/amark/gun/issues/398 Point2)
And could SEA cover those role/permission scenarios .

**Comment by amark** [comment]
@Devric welcome!!!! :)

Yes, SEA is in alpha right now, and all those things are possible/intended:

 - With SEA, a user can use multiple devices and sync in realtime.
 - With SEA, you can collaborate with other users - however, we're currently working on "shared objects" in the alpha, it isn't finished yet, but coming soon. Please give it a try though!
 - Yes. :)

Q1. As long as your server peer is using gun as the "gatekeeper" everything should work. People have already created adapters for other databases with https://github.com/sjones6/gun-flint , including MySQL, Mongo, Cassandra, Level, and others. I don't recommend mixing databases, but if done properly, it can work.

Q2.

 - If you make each 200 items be a sub-object of the user, then those sub-items will ONLY BE LOADED with gun if a user specifically requests them. This way you can map over a large user base, without actually loading all the details. :) GUN already works like this, we can help more/provide examples in the chatroom, here: https://gitter.im/amark/gun
 - With SEA, right now, all data on a user's graph is write-only by them, and by default most of it is public-read. It is fairly easily to manually make it write&read-only using the utility functions, however doing multi-write or group-read you'll probably want to wait for us to finish SEA (no longer in alpha). We explain how the cryptography of all of this works, here: https://gun.eco/explainers/data/security.html
 - Your remaining examples are good examples of various combinations of things, some of which we already support, some of which we're working on making easier. NOTE: SEA is fully P2P/decentralized and doing end-to-end encryption, it has no concept of "download" because data is protected regardless of who stores it (it is encrypted, they can't access it). If you are wanting a central server to control who access and downloads what, and how, we're looking for somebody to build out a centralized security framework for this - somebody has written a very short example of how to kinda do this: https://github.com/zrrrzzt/bullet-catcher .

GUN instances: Yes, it is easier to keep and sync all data in the same instance, but isolate/separate the data by is structure.

GUN sync: Generally speaking, gun syncs the data that is requested via its API, however it doesn't really have a concept of remotely controlling who "downloads" what, because it is P2P/decentralized. In P2P environments, the network topology is distinct from your business logic topology, as an example:

Think about your physical WiFi router and ISP or your cell phone provider. You might have Verizon as your carrier, but you might be connecting via AT&T towers. P2P systems might "daisy chain" through other computers/networks in order for 2 peers to sync with each other, even if the peers inbetween don't care about it. Does this make sense? Let me know if you want me to explain more.

SEA is already capable of doing all those things, however some of them are already done automatically when you call GUN's API, and some of them you'd need to either use SEA directly [currently in alpha, no docs yet, but we can help you on the chat room] or wait for us to finish implementing the framework.

@Devric I highly recommend you jump into the chat :) a lot of people provide help there. I'll probably wind up closing this issue soon since it is more a question/help than a bug report. Let me know if you have any other Qs though!

**Comment by Devric** [comment]
Thanks, Mark. 👍 clarification.

Just played around with SEA also had a quick scan at the code ( I can see it is Alpha stage, the API is a bit messy in terms of the callbacks/promises it try to return. probably could standardise the return Object/Msg a little for all SEA methods. and it is using SPREADS which only work in Chrome and Firefox at the moment, any consideration using babel for the next SEA build?) 

Another question on the Peer part, I just realised everything is encrypted, so in your vision, what can the PEER do or cant do as a gatekeeper for 

- authenticated data.
- non authenticated data.

Also Not sure if it is a bug or i didn't do it correctly, if i tried to wrap a function like below, it will only work on the first call, the consecutive calls will not yield any result, even though the data are still in local storage.

```
(user, pwd) => {
    user.leave()
    user.auth(user, pwd).then(()=>{
          user.val(console.table)
    })
}
```

**Comment by amark** [comment]
@Devric :) I'm curious, what is your project you are working on?

Most of SEA has been the work of @mhelander who is a genius. He requested ES6 code since WebCrypto requires latest browsers anyways, and he had mentioned stuff about Babel - I'm not smart enough to understand how that stuff works :P (I write all ES5 code), so maybe you can help him out with getting that to work. Yeah, we've been refactoring a bunch of stuff so expect things to be breaking/changing, but ultimately becoming more consistent.

If you are using SEA, a server-peer won't really be able to do anything other than backup data to a more reliable storage system (like S3, etc. hopefully IPFS in the future) and provide better peer connectivity (data will automatically sync between peers connected to the server-peer, it acts as a hub, at least until WebRTC gets improved).
Although, somebody recently suggested that a server-peer could be a "bot" (ie, itself have a user account) which sounds like an interesting option to open up more server-specific behavior.

If you are intentionally trying to limit total storage a user can store (to prevent your S3 cost/bill or similar from being exploited) then it sounds like you are building a much more traditional SaaS like app, which will probably be easier for you to build your own custom centralized security system (SEA is very P2P which doesn't always jive well with SaaS like apps). For myself, I hope in the future it will be easy for users to pay for their own storage via GUN +Filecoin or similar. @robertheessels already has some ideas on how to combine Sia/IPFS to handle stuff like this.

Hmm, that may be a bug (I thought I had fixed that), so maybe open it up as a separate issue. Although note, any `user` method is technically a gun chain context, and it will always return a chain (not necessarily a promise. However the `lib/then` extension does downgrade chains into promises, however in the case of "auth" the downgrade is to the user's account [their data], not necessarily the login event).

See you there! (And other issues as they arise :P)

**Comment by stephenh** [comment]
FWIW I came across gun while looking for an offline-first, JS-/ReactNative-friendly data store, and am really impressed: runs everywhere, has conflict resolution built-in, even has reactivity for UI updates. Really slick.

That said, I'm with Devric of wanting old-school/boring "fake security" :-) of a centralized, multi-tenant server applying Firebase-style auth rules to data coming in/going out, e.g. user X can/cannot access node Y based on rules Z.

AFAICT that doesn't really exist for gun today? I'm a little surprised, because surely existing production deployments have some amount of SaaS-style security/auth involved.

Totally fine that you're excited about p2p/IPFS/etc.-based security but again FWIW, from a potential gun user, that's a bit over my head :-), and not really a use-case I'd need.

(Wasn't sure the best place to leave this feedback, so hope this was okay. Thanks!)

**Comment by amark** [comment]
@stephenh hey :) welcome!

Some people in the community have some started showing some simple examples of how to go in that direction. For instance:

https://github.com/zrrrzzt/bullet-catcher

Gives a very basic sample of how you might implement a JWT session token.

We'd absolutely love it if you contributed a full featured centralized auth framework with Firebase-like rules. We'll absolutely link to it and promote it :).

However, our team is likely not going to build it - or if we did, it would be proprietary and we'd charge for it, which is kinda lame/boring. Having a centralized authority is just not in our roadmap, though.

And yes, actually! All our current security deployments are fully P2P with SEA (our security framework). It is actually very easy to get started with it to build things like Twitter and stuff:

https://gun.eco/docs/Auth

It removes the "confusing decentralized" blah blah stuff, and just works, and is much more scalable than any centralized auth system (part of the reason why we aren't planning on building centralized auth). :) If you don't like it, that is okay, you don't have to use it, try out bullet catcher and let me know if you can help contribute.

Cheers!

**Comment by stephenh** [comment]
Nice, I'll check out bullet-catcher.

> or if we did, it would be proprietary and we'd charge for it, which is kinda lame/boring

Hehe, yeah, makes sense. If I were to build that, I would do the same thing. :-)

Thanks for the response!
