### ISSUE TITLE
`.all`

### ISSUE THREAD

**Issue by metasean** [amark/gun#53]
Adds functionality to retrieve all existing keys.

**Comment by amark** [comment]
@Stefdv I added this to the default disk file.js storage adapter. Unfortunately it is a per-storage-driver implementation specific detail. You have to manually call `gun.on('out', {get: {'#': {'*':''}}})` to trigger the lexical cursor request, message me for more details.

Because this is now implemented in SOME places as a prototype. I'm gonna close.
