### ISSUE TITLE
Gun and Hyperdb

### ISSUE THREAD

**Issue by fredhampton** [amark/gun#530]
What are the differences between Gun and Hyperdb https://github.com/mafintosh/hyperdb ?

**Comment by amark** [comment]
HyperDB uses append-only logs that must necessarily be cryptographically secured.

GUN uses a simpler CRDT model that you can learn more about here https://gun.eco/distributed/matters.html .

CRDTs are generally more scalable and faster to sync than append-only logs (why? Because they are history-independent).

You'll be able to have either bidirectional graphs OR directed graphs (DAGs) in GUN, but looks like HyperDB only supports directed graphs (aka, an append-only log).

Those are probably the biggest differences, if I read their architecture page correctly, our architecture is explained in this tech talk and corresponding docs: (see the sidebar) https://gun.eco/docs/Porting-GUN .

If you could copy&paste this into StackOverflow tagged gun that would be super appreciated (so that way others can see your question, and see you for contributing it!!!)! We try to keep GitHub issues for bug reports, so closing here. If you have any further questions, just update the StackOverflow - thanks in advance!

**Comment by noffle** [comment]
[hypercore](https://github.com/mafintosh/hypercore) (the piece powering hyperdb) can do selective replication from peers, effectively letting you sync arbitrary subsets of data without compromising the cryptographic integrity of the logs.
