### ISSUE TITLE
ECDH is not a supported algorithm

### ISSUE THREAD

**Issue by zer09** [amark/gun#552]
I run onto this when tried to use ```gun.user()```.

When creating new user I am just getting ```SEA.create failed!``` and tried to dig deeper and found that ```SEA.pair()``` will return ```undefined``` untill I found this.

```
{ Error: ECDH is not a supported algorithm
    at SupportedAlgorithms.normalize (/mnt/Time Machine/guntest/node_modules/@trust/webcrypto/src/algorithms/SupportedAlgorithms.js:78:16)
    at SubtleCrypto.generateKey (/mnt/Time Machine/guntest/node_modules/@trust/webcrypto/src/SubtleCrypto.js:199:51)
    at Function.SEA.pair (/mnt/Time Machine/guntest/node_modules/gun/sea.js:337:48)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) message: 'ECDH is not a supported algorithm' }
```
 
Actually I add this https://www.npmjs.com/package/@trust/webcrypto and on there [Supported Algorithms](https://www.npmjs.com/package/@trust/webcrypto#supported-algorithms) ```ECDH``` is listed as not supported.

I am missing something here or I installed the wrong library?

thanks

**Comment by amark** [comment]
Oh, yes! Thank you @zer09 for posting this... I thought I had replied here as well, but I guess I only replied via gitter.

Your summary about `@trust/webcrypto` not yet supporting ECDH is the important observation. I don't want to force people to have to install all of Python just to get ECDH working - hopefully `@trust/webcrypto` will add support soon in NodeJS.

@zer09 it sounds like my gitter suggestions worked? If so, please confirm and I'll try to make it so OSSL works automatically if it happens to be installed - so that way people don't have to uncomment any code.

**Comment by zer09** [comment]
yes ```SEA.pair()``` is working, I was able to create the keys, but not that quite working using this example https://codepen.io/anon/pen/QajxOz?editors=1012 it can create the user but unable to authenticate. I am still looking was is the cause for now.

**Comment by zer09** [comment]
@amark the ```crypto``` here is not defined.
https://github.com/amark/gun/blob/aca0497fd5f76acfc3eacc6ca0385d37195f0f70/sea.js#L290-L296

It successfully save the ```user``` without an error but the ```auth.ek``` is missing. I tried to put ```require``` for ```crypto``` and it works as expected. Should I do pull request? :smile: 

Thanks

**Comment by amark** [comment]
@zer09 ah, thank you for spotting this, it must be an accidental crossover between the automatic `ossl` references vs downgrading to `@trust`.

Yes please send a PR. I'll probably have to immediately edit it, but at least it'll help me understand what to do better. Thank you!!!

`sea.js` is the file that should be edited, we don't have our build/unbuild fully working. Most systems are NodeJS -> Browser in their build step, going from /src or /sea to a src.js or sea.js, because we build everything Browser first, we "unbuild" from Browser -> NodeJS, causing sea.js -> /sea, however the design of the "unbuild" system will ALSO allow us to /sea -> sea.js or sea.js -> /sea so that way any developer can contribute regardless of their preference. I just have finished it yet, so please edit `sea.js` directly in the PR.

You rock @zer09 !!!

**Comment by amark** [comment]
@zer09 THANK YOU for the pull. It has been merged, and using your code as an example, I was able to improve it and other places (other code that depends upon ECDH), and it is now NPM published. You are an official contributor :D :D :D 👏 👏 👏 !

Here is what now happens:

 - Using SEA with GUN in NodeJS without installing the crypto libraries produces a warning/error that you must install the crypto libraries.

 - Once the crypto libraries are installed, SEA will work but does not include ECDH by default (often not needed in NodeJS) and will work correctly for non-ECDH operations, but log warnings that ECDH errors will/could/may happen. It will also tell you to install the OSSL library if you need it.

 - If OSSL library is installed, then everything should just work out of the box!

I'd love it if you could confirm that things are working for you with OSSL in the lastest GUN version. Thanks so much for helping out with this! Closing, thanks to your PR!

**Comment by zer09** [comment]
Sorry but I am getting this ```node: symbol lookup error: /mnt/.../guntest/node_modules/node-webcrypto-ossl/build/Release/nodessl.node: undefined symbol: OPENSSL_add_all_algorithms_noconf``` on ```0.9.9991```
