### ISSUE TITLE
No data stored for keys starting with "us" when using RAD

### ISSUE THREAD

**Issue by ryanfields** [amark/gun#563]
I'm using Gun v0.9.999 and seem to have encountered a bug where keys that start with the letters "us" are not persisted to disk when using RAD.  When I run the following code example, an radata folder is created, but nothing is written in it.

```
const Gun = require('gun')
const gun = new Gun({ localStorage: false, radisk: true })
gun.get('us').put({ test: 'some data' })
```

So far, anything I've put after "us" has the same result.  Examples: "usa", "usregion", "us locations".  As soon as I change the key to something else like "test", or even just "u", data is written as expected.

**Comment by amark** [comment]
@ryanfields thanks for this report, I think it might be related not to RAD but with the most recent async/sync debacle of tests that weren't running. This is now fixed in 0.9.9992+ could you retry?

It certainly could be a RAD issue still, even with 0.9.9992+ we're still combing through bugs with RAD.

**Comment by ryanfields** [comment]
I just tested it on 0.9.9993 and it's working as expected.  Thanks!

**Comment by amark** [comment]
Yay!!! Thank you.

Note! There are still some known significant issues with RAD. So beware while using it.
