### ISSUE TITLE
map completes

### ISSUE THREAD

**Issue by jadbox** [amark/gun#565]
When doing once().map().once(), is there a way to know when the stream has been exhausted?

**Comment by amark** [comment]
@jadbox there was an extension called `valMapOnce` (I think) that did this (it probably needs to be upgraded to latest), the code is pretty simple but not as chain-able.

The problematic thing about this, is that streams are technically never "done" - but even if we ignore that (since `once().map()` treats it like a stream that does "finish" at a certain point in time)... is that using `undefined` or `null` or other symbols to represent "done" are kinda problematic and create non-homogenous/uniform processing logic.

I (previously, old old old versions ago) used to require even storage adapters to send a terminating sequence, but it wound up being a terrible design.

My most recent thoughts, which might be easier than I think, is to add a special event hook (rather than a special terminating sequence / symbol), something like `get('list').once().map().once().on('end', cb)` or similar. Would this be decent? (it might have to be chained off the table, not the map, but yeah... something like that)

I still might have this be done as an extension/plugin, rather than in core. I don't want to bloat core, but I'm okay with lots of extensions being created for people to use.

**Comment by jadbox** [comment]
Going to think on this, because I can see your point about the "stream is never done" but it also causes severe limitations. Also, it makes the api a little strange when most methods can be await'ed on, but this doesn't work for collections. 

I've made this hack for now... it's not terrible but it's not ideal either. It basically looks for the list of keys in the collection object and the streams results until the length has been hit. Suggestions are welcome:
```
const results:[]any = _listify( gun.get('users') );

async function _listify(gunPath: any, getHead: boolean = true): Promise<any[]> {
  const listVal = await gunPath
  delete listVal['_'] // remove gundb key first, before reading key length
  // get all keys with values
  const len = Object.keys(listVal).filter((k: any) => !!listVal[k]).length

  if (len === 0) return Promise.resolve([])

  let count = 0
  const total: any[] = []

  return new Promise<any[]>((resolve, rejected) => {
    let m: any = gunPath.map()

    m.once((x: LCState, index: string) => {
      // TODO find a way to track keys
      if (!listVal[index]) {
        console.log('warning: discarding new entry since list key reading')
        return
      }
      count++
      if (!!x) total.push(x)
      if (count == len) resolve(total)
    })
  })
}
```

**Comment by jadbox** [comment]
btw, is there a way to initialize a key as an empty set in Gun?

**Comment by jadbox** [comment]
For my last question, this seems to work to initialize a list:
`await node.get("users").set(null)`

**Comment by amark** [comment]
@jadbox sorry for not having followed up. **THANKS** for the snippet. In the future, I'll keep in mind having tighter integration, but your snippet is good evidence of how to build a better promise features / extensions on top of GUN, which (for now) is going to be the official way to do it (I have too heavy of a load myself right now to maintain it in core). Thanks again, closing! ++ ping, would love to hear updates.
