### ISSUE TITLE
Production-ready disk implementation

### ISSUE THREAD

**Issue by metasean** [amark/gun#57]
If there are many consecutive writes using the default test implementation, i.e. the file.js implementation, the disk is unable to handle the load and errors.

Currently, the only time file.js implementation should be used with gun is in local testing.  In production usage, Amazon S3, Google Cloud Storage, localStorage, or an equivalent cold storage persistence layer should be used.

Note: This is a very low priority for the gun team.  If this functionality is intriguing to you, please feel free to volunteer and start working on a modular implementation.

**Comment by amark** [comment]
From the community discussion, it looks like integration with **Level** (`npm install level`) is highly desired as the disk engine layer. If you want to help integrate please let us know! It should be fairly easy, porting either the S3 or localStorage module to use Level instead.

**Comment by amark** [comment]
Trying to tag all issues that have existing Level mentions that @PsychoLlama wrote https://github.com/PsychoLlama/gun-level so we now have support! And to potentially merge and close all those issues. @metasean could you check into this at some point? I've made it easier since I've referenced Jesse's work in all the threads I think relate.

**Comment by metasean** [comment]
At this time, we recommend the use of https://github.com/PsychoLlama/gun-level
