### ISSUE TITLE
Storage exceeding quote

### ISSUE THREAD

**Issue by mitra42** [amark/gun#590]
Seeing this error in the browser console log while retrieving. The retrieval is going through our "hijacker" at the server, but shouldnt be seeing this. 

> Failed to execute 'setItem' on 'Storage': Setting the value of 'gun/' exceeded the quota.

**Comment by mitra42** [comment]
See https://github.com/internetarchive/dweb-archive/issues/46

**Comment by rebootcode** [comment]
I believe the allowed permission-less storage capacity of the browser on the desktop is only 50mb and in mobile is 5mb.

Beyond this, you will need permission from the user to store access data.

**Comment by robertheessels** [comment]
You can now opt in to use IndexedDB, which has virtually unlimited space (up to half of free disk space).
See lib/rindexed.js

**Comment by amark** [comment]
Yeah, quick (temporary) example of how to add it to the browser:

https://github.com/amark/gun/blob/master/test/tmp/indexedDB.html

**Comment by mitra42** [comment]
P.S. I don't mind if something pops up on the browser Asking for permission, at the moment I suspect most apps will fail silently at this point (dweb-archive app just switches back to http when gun starts failing)

**Comment by amark** [comment]
Totes agree, it is easy enough for anybody in the community to add a build script to bundle them together, then it'll be a 1-line drop in. I just don't have time to waste doing it myself cause it takes me 10 hours to figure out how webpack/gulp/junk work (I wasted 3 hours the other day on some stupid gulp/babel problem), but I'll more than super happily accept a PR.

**Comment by mitra42** [comment]
It would help if the example at https://github.com/amark/gun/blob/master/test/tmp/indexedDB.html was understandable, on the phone we clarified that jquery wasnt required and looks like that is removed.  but I can't figure out ... 
```
var opt = {};
opt.store = RindexedDB(opt);
var gun = Gun(opt);
```
Does this mean I have to call RindexedDB to get the options to pass to Gun, and having opt on both sides of that middle statement looks really weird. It clearly can't work this way in most apps which will include the libraries in one place and now can no longer pass a typical opt dictionary to Gun at startup since if I read the above code-fragment correctly I have to call RindexedDB to get something to pass t Gun, and RindexedDB is not going to be in scope at the level the opt dictionary is being built.

**Comment by mitra42** [comment]
To be clear ... even if you follow the instructions in https://github.com/amark/gun/blob/master/test/tmp/indexedDB.html in node, they don't work.  `RindexedDB` isn't defined, and it doesnt work if you do the obvious correction of `var RindexedDB = require('gun/lib/rindexed.js')` because `opt.store = RindexedDB(opt)` fails with `window is not defined`.

**Comment by mitra42** [comment]
Note ... questions were asked about this on Gitter, without any reference to this issue, so copied below since chance of finding on Gitter are ~0% :-) 

```
Mitra Ardron @mitra42 11:43
@amark Sorry - just saw your question a couple of days ago. Note I’m not watching this gitter chatroom as covers too many topics so I can’t just watch issues I’m following.
You asked: "Help me understand - IndexedDB is a browser technology, not a NodeJS library. Is the goal the thing we talked about yesterday about... writing it in a NodeJS syntax so Webpack packages it in a single bundle? But it is crashing?” I’m not sure what that was in reference to … but ..
The goal would be to have a single script that could be included (either including, before, or after the <script> so that it could be web packed) along with whatever else was webpacked together (GUN, app code etc).
My attempt at translating your script tags into node failed for two reasons - first because my attempt at converting to node “require” syntax failed, and secondly I hadn’t figured out the weird use of opts, which if I remember correctly passed opts to something, then used the result to modify opts before passing to Gun. I can’t find whatever I wrote, because the question is here, rather than in the GIT issue so I’m only seeing it out of context.

Mitra Ardron @mitra42 11:59
@robertheessels, You asked on Sept 22 and again, sorry I missed it - I’m not watching this busy Gitter channel continuously: "Why would you want to use IndexedDB in node? The default RAD storage in node is already doing something similar, right?” .
What I’m trying to do is include GUN into the dweb-transports library which is then included in either Browser or Node applications such as [https://dweb.archive.org] or dweb-mirror. That means using a node format (require / import) and then webpack. Currently it breaks in browsers because the browser with the minimal GUN runs out of local storage. @amark ’s solution is a set of script tags and (strange) javascript that should go in a webpage, of course I have to put that into a set of require statements and initialization to go in dweb-transports, but the obvious translation from <script> tags didn’t work and was reported in amark/gun#590.
Its quite possible the problem was using it in node rather than testing in browser console, I was just trying to step through trying a non-obvious translation from script tags to javascript lines. At this point I don’t have a way to include Gun in our library so that (when called with appropriate opts) that it works in both Browser and Node. (This is trivial by the way in IPFS).
```

**Comment by mitra42** [comment]
Just flagging that this issue persists, Gun has been broken in my browser (and presumably for anyone else using Dweb.archive.org for more than a few pages) for close to a year because while "trivial" @amark hasn't got time to fix it, and noone else appears to be able to figure it out.

**Comment by amark** [comment]
@mitra42 RAD + IndexedDB fix has been available for a long time now, and has had docs published for a while (not as long) at https://gun.eco/docs/RAD#install .

I'm still confused at you wanting to use IndexedDB in NodeJS? It seems you want 1 script tag for the browser, that also has all the NodeJS dependencies? This would unnecessarily bloat your browser with a ton of NodeJS code (as NodeJS uses `fs` instead of `IndexedDB`).

That just seems like a terrible idea. What stops you from using X files for browser and Y dependencies for NodeJS?

**Comment by mitra42** [comment]
@amark to be honest I'm looking at this again, after having GUN broken in the browser since September ...  I tried to get clarification then even on the browser-only question, but got no respinse and gave up and left it not working, didn't notice till now since our dweb-transports library works around GUN not being turned on (backing off to HTTP or Wolk) 

The problem - as explained back then is that there is one library, (the dweb-transports repo) that is used transparantly in both node and browser applications, but I can't currently get GUN to work in either browser or node, never mind a combination. Browser has been broken for a while (as reported here) and I just noticed that node was broken as well when I tried to turn it back on in the dweb-mirror application (prompted by your message in  the dweb-camp repo)

**Comment by mitra42** [comment]
I have to head out now to a meeting, and it must be late in California, but would be happy to try a call tomorrow and try and fix it.

**Comment by amark** [comment]
@mitra42 we keep saying the same thing at each other, why is their miscommunication?

Your [September](https://github.com/amark/gun/issues/590#issuecomment-424559364) comment says I helped you in the chat room with the browser issue, with (as you quoted) "solution is a set of script tags". Your [other comment](https://github.com/amark/gun/issues/590#issuecomment-423716692) then says "indexedDB.html in node" - which, I hope you understand, is where I am extremely confused:

 - I give you a browser solution.
 - You use it in NodeJS.

That didn't make sense to me. Also, add into the fact, that I know you do have a NodeJS GUN system running, so I figured you already knew how to do NodeJS, just not Browser.

Please understand, I'm trying to help you.

It seems like the main point things are boiling down to is:

You **want** a Browser script that **includes** NodeJS bloat? So that you can reference **a single file** (not a package) from the Browser or require it in Node? And this file must have both environment's dependencies inside of the file, with no requires allowed inside it?

From my perspective, it is very odd that you'd want NodeJS bloat included in the browser distro, and probably where our miscommunication is coming from, but if that is the hard requirement because the library your shipping when it runs in other people's NodeJS instance cannot rely on some package system, then that actually makes sense. Basically, you're treating the other NodeJS instances as if they are browser-like, that machine has to fetch something, and it isn't going to fetch it from NPM/etc., so all the code needs to be in the same single file. Yeah? If so, please confirm, and I'll try to figure something out.

**Comment by mitra42** [comment]
Conclusion today ... to uncomment lines in TransportGUN that include rindexed.js and then try and sort out what problems if any occur in using it from Node (dweb-archive internetarchive/dweb-archive#46)

**Comment by mitra42** [comment]
Conclusion today ... was to uncomment lines in TransportGUN that include rindexed.js and then try and sort out what problems if any occur in using it from Node (dweb-archive internetarchive/dweb-archive#46) 
This worked in webpack ... but failed during connection. 
```
store.js:12 Uncaught (in promise) TypeError: Radisk is not a function
    at Object.eval [as next] (store.js:12)
    at Object.eval [as next] (multicast.js:4)
    at Object.eval [as next] (gun.js:1868)
    at Object.eval [as next] (gun.js:1854)
    at Function.onto [as on] (gun.js:197)
    at Function.Gun.create (gun.js:686)
    at new Gun (gun.js:654)
    at Function.setup0 (TransportGUN.js:106)
    at eval (Transports.js:649)
    at Array.map (<anonymous>)
    at Function.setup0 (Transports.js:642)
    at Function.p_connect (Transports.js:719)
    at main (archive.html?identifier=home:95)
    at archive.html?identifier=home:107
```

**Comment by amark** [comment]
@mitra42 sounds like you fixed this the other day by switching the script tags in the [documentation](https://gun.eco/docs/RAD#install) to require:

```
require("gun/gun.js");
require("gun/lib/radix.js");
require("gun/lib/radisk.js");
require("gun/lib/store.js");
require("gun/lib/rindexed.js");
```

Right? If so, closing. If I'm we're still missing something (with respect to this issue, the browser), please reopen.
