### ISSUE TITLE
Linting Problem with Constructor

### ISSUE THREAD

**Issue by alexlafroscia** [amark/gun#6]
When JSHint-ing whatever sets up the Gun connection with

```
var gun = Gun(...);
```

I keep getting the following warning:

> Missing 'new' prefix when invoking a constructor.

Should we require `new`?  I know that it works right now, but if it doesn't follow JavaScript's normal patterns then we should at least discuss bringing it in line.

**Comment by amark** [comment]
GUN figures out whether you need to use `new` for you:

```javascript
	function Gun(opt){
		var gun = this;
		if(!Gun.is(gun)){
			return new Gun(opt);
		}
		gun.opt(opt);
	}
```

So that way you don't have to worry about it. I think you can call it explicitly and it'll still work just fine `var gun = new Gun(...);` but I should probably write tests to guarantee that. This just protects against common forgetfulness and it doesn't have any side effects.

**Comment by alexlafroscia** [comment]
Okay, cool.  It's more that I want to make sure that using `new` still works, since my linter is throwing a warning whenever it comes across not using it.

**Comment by coolaj86** [comment]
I had suggest exposing a '.create()' method, as that's the conventional way to expose the constructor when you want to avoid new.

**Comment by metasean** [comment]
[Documented](https://github.com/amark/gun/wiki/JS-API#var-gun--gunoptions).  @PsychoLlama may make an extension which adds a `.create()` method.

**Comment by PsychoLlama** [comment]
`Gun.create()` has been added as a code snippet, found [here](https://github.com/amark/gun/wiki/Snippets#guncreate-to-instantiate-without-new)
