### ISSUE TITLE
DDoS or Flooding attack

### ISSUE THREAD

**Issue by datnguyencse** [amark/gun#630]
Hello Gun's team, thank for your great work.

What will happened if I try to do a simple attack to a gun network by write few terabytes of data to it. Is it possible and how to prevent.

Thank you.

**Comment by amark** [comment]
Sorry, super behind on my GitHub issues.

@datnguyencse would you mind Copy&Pasting this to StackOverflow tagged gun?

 - So far it has been able to handle terabytes!!! P2P reddit reported doing a half TB in the first day of launching. Lot more since then.

 - http://AXE.eco/ is designed to punish DDoS/Flooders, but isn't finished yet.

 - If you have a way to differentiate between an "attacker" or not, then yes, peers could drop daisy chain relaying (https://gun.eco/docs/DAM) messages to protect others on the network.

But take note, people pushing TB of traffic != an attacker. So the more important thing is that GUN can handle TB of traffic - although this is more a limitation of hardware than it is of GUN.

**Comment by amark** [comment]
@datnguyencse and to follow up, would love to hear what you are working on!?? How'd you find out about GUN? I think you jumped on the chatroom and asked the Q too, right? WELCOME TO THE COMMUNITY!!!! :) :) :)

I try and save GitHub issues for bugs, so I went ahead and closed. Your Q is good, and it helps others a ton, if you could make it visible on StackOverflow instead, so please remember to copy it!

**Comment by datnguyencse** [comment]
Thank you @amark, also can you take a look on this lib https://github.com/libp2p/js-libp2p - a very good DHT lib

**Comment by amark** [comment]
@datnguyencse libp2p doesn't have the flood prevention that DAM already has, SSB also has something similar to DAM. I'm not aware of IPFS being at this stage yet.
