### ISSUE TITLE
error for subscribe

### ISSUE THREAD

**Issue by mccoysc** [amark/gun#649]
gun.get('topic').get('data').map().on(function(d){
    console.log(d)
});

gun.get('topic').get('data').set(1).

the above code would work well.
but,after the following code,the on's callback function would nerver be called any more:

gun.get('topic').get('data').put(null).

though i call any times of :
gun.get('topic').get('data').set(1),gun.get('topic').get('data').set(2)  and so on……nothing is working

**Comment by mccoysc** [comment]
in fact,i expect that after .put(null),if call .set(1),all data in set would be in new state but not in fact.

**Comment by amark** [comment]
Hmm, I'm pretty sure I have a test for this in core, because it took like 5 months of my life to figure out how to solve for this.

But my philosophy is to assume any reports like big thanks from @mccoysc is true because tests only test what they know to test, and there is nothing more thorough than people like you helping find edge cases! So thank you, IDK how soon I can get to this though :/ pretty back logged with stuff just getting back from Japan. I was gone this last week, sorry for the delay to reply - forgive me.

**Comment by amark** [comment]
I'm hoping my fix for https://github.com/amark/gun/issues/632 will fix this as well, when next version gets published please retry.

**Comment by amark** [comment]
I published the SEA security fixes earlier today, they should have included the previous fix for this + #632 and it should now be available in latest ...92 version.

Please upgrade and try again! Should be fixed, so closing - please reopen if you notice any other problems.

Thanks again @mccoysc for reporting this!!! :) :) :) Grateful for people hunting down and reporting problems, even if it takes me a while to fix/patch them.
