### ISSUE TITLE
Contribution Guidelines?

### ISSUE THREAD

**Issue by bugs181** [amark/gun#654]
Apologies if there is already a reference to this. I'm looking to contrib back to Gun/SEA/AXE however found no contributor guidelines. For example, I have my editor set up in such a way that's it's optimal for my environment. (Tab-spacing, linting, etc.) How specific do we need to be, to adhere to any guidelines for contribution?

**Comment by amark** [comment]
Pretty much all contribution so far has been possible in user-land due to the modular nature of the ecosystem/stack - in which case, DO WHATEVER YOU WANT :D :D :D :D :D it is your project.

For anything that is going to be considered so core that I also may have to help maintain, then, the general preference is:

 - ES5 or lower.
 - MIT/Zlib/Apache2.
 - Functional > Procedural.
 - Progressive Enhancement.
 - No dependencies.
 - Small.

Moral of the story is it is possible to do near C/C++ level performance in JS (shockingly) and in just a couple of lines where most people write hundreds.

Here are some references:

https://www.youtube.com/watch?v=BEqH-oZ4UXI
https://github.com/amark/theory

I could probably do a whole hours of talking on this subject of good/quality code (it is very heretical and controversial compared to most "best practices" junk out there). If you ever have questions, just ping me on gitter and I'll try to reply fast.

However note: If you are having to follow my guidelines, that either means (A) it isn't modular enough cause most things should be done in user-land or (B) you are writing meta-meta-meta level code that is so core to the entire internet and humanity that :P we need to be best friends.

:)

**Comment by bugs181** [comment]
Clear and concise enough for my pleasure. Closing. 

P.S. I think we should be best friends anyway. You're my hero! lol.

**Comment by amark** [comment]
That is sweet of you. :) :) :)
