### ISSUE TITLE
disk[soul] is null

### ISSUE THREAD

**Issue by mccoysc** [amark/gun#657]
`			var gap = Gun.obj.ify(store.getItem('gap/' + opt.prefix)) || {};
			var empty = Gun.obj.empty,
				id, to, go;
			// add re-sync command.
			if (!empty(gap)) {
				var disk = Gun.obj.ify(store.getItem(opt.prefix)) || {},
					send = {};
				Gun.obj.map(gap, function (node, soul) {
					Gun.obj.map(node, function (val, key) {
						send[soul] = Gun.state.to(disk[soul], key, send[soul]);
					});
				});`

at gun.js line 2725-2737:
some time,store.getItem(opt.prefix) is null and make disk is {}.
so make disk[soul] is null.
and then make Gun.state.to(disk[soul], key, send[soul]) throw an error.
@amark

**Comment by amark** [comment]
@mccoysc good observation, do you by chance have the stack trace on the error call log?

If I look at the code, it shouldn't crash though, because `disk = THING || {}` should safely fallback to `{}` in case it doesn't work. But if you see it crashing, then I need to fix.

Need to also move re-sync command to be storage-agnostic, but that is for another time.

**Comment by mccoysc** [comment]
@amark that i know why:
when start,you read from localStorage key "gap/gun" and these data is that whcih have not been sent and should be re-send.
but these data is only the msg "key",no data.
so you read from localStorage key "gun/" (default,all data is saved in this key).
but in my case,i config options with "localStorage:false" and all data is saved to another storage adaptor by myself.
no any data is saved to the key "gun/",so disk woould be "{}".

**Comment by mccoysc** [comment]
to resolve this issue,maybe, the re-sync logic should be changed.
for example:don't use local storage to store any data,but using the "gun.put" and "gun.get" interface.

**Comment by mccoysc** [comment]
or you can add a way which supply storage interface like setItem,getItem and so on.and then if user confi "localStorage:false",the user sould supply these intwerfaces.

**Comment by amark** [comment]
@mccoysc ahhhhh yeah that makes sense. THANK YOU.

I've fixed this in a local commit, it should go out in the next version release.

Also, @jacobpdq you mentioned something similar in the chatroom this morning, @mccoysc figured it out! :)

Should be fixed in next release. Closing!

@mccoysc thank you for analyzing this!!!!
