### ISSUE TITLE
error on Date property

### ISSUE THREAD

**Issue by steve-vincent** [amark/gun#693]
```
obj.date = new Date();
gun.get('mydata').get(id).put(obj, function(ack){console.log(ack);});
```

gives
`Invalid value at '<my id>.date'!`

I can work around by not storing data as native Date type, but just fyi...
The id I used is long alphanumeric with hypens and decimals.

**Comment by amark** [comment]
@steve-vincent thanks.

Yeah, `Date` is different in different languages, so GUN requires you to save `date.getTime()` (the UTC timestamp number, is recommended over the string you mention) so that way other machines/languages/peers can take the UTC number and put it into that-language's native `Date` constructor (which is different than JS's).

So this technically isn't a bug - but maybe you could add this as a more explicit comment/note in the API `put` docs? (docs pull from github.com/amark/wiki which anyone can edit), it should currently say what **is** allowed, but doesn't list everything that is **NOT** allowed.

Closing!
