### ISSUE TITLE
Filtering null doesn't work in .map()

### ISSUE THREAD

**Issue by cbeninati** [amark/gun#704]
Maybe I've misunderstood the intention of `map()`, but I'm trying to use it to filter out any 'deleted' or 'null' results, but unlike filtering on existing properties, it fails.

**Currently**
Currently, I need to add conditional logic inside the `map()` callbacks.
```js         
this.user.get('things').map().on((thing, id) => {
  if (thing) {
    // Thing is not null/deleted. Do something.
  }
})
```
**Desired**
I'd prefer to use a filter inside `map()` for nullable values.
```js         
this.user.get('things').map(item => item !== null).on((thing, id) => {
  // Thing is not null/deleted. Do something.
})
```

**Comment by amark** [comment]
@cbeninati yes, it actually works very similar:

```
user.get("things").map(function(thing, id){
  if(thing !== null){ return this }
}).on(cb);
```

`map` takes a function that does transform + filter + forEach.

Anything you `return` from the map gets passed on, so in your "example" you'd be returning `true` which would cause `true` to show up in the `.on`.

The one special case `return` value is `undefined`, if `undefined` is returned, that item is not passed forward.

Since what is returned is passed onward, it is useful to use `return this` to pass the gun reference forward as normal, although you could also do `return data` which should behave the same way.

I hope this helps?

++super points if you update the github.com/amark/gun/wiki API docs (the gun.eco/docs site pulls directly from the GitHub wiki which anybody can edit).

Closing. :) Please ask any other Qs though!
