### ISSUE TITLE
GUN to Relational Database for Reporting Services

### ISSUE THREAD

**Issue by merarischroeder** [amark/gun#715]
Feature request.

There are no major reporting engines that support GUN (nor most NoSQL DB systems). My solution for this kind of issue is to:

1. Architect the NoSQL database, treating each collection like a table, with only a single tier deep of records; AND
2. Have a general software system that subscribes to each collection, and inserts/updates records in a relational database.

I'm sure many coders can repeat [2], and do it in all kinds of mind-bending ways. But ideally, each NoSQL vendor does this kind of thing once and well. I'm sure there are unique features with each NoSQL database system to ensure the integrity and timeliness of relational reporting data. 

(Also, there's a chance to use a streaming SQL language so that special reporting results tables can be built live, and aggregate results can be maintained for ready near-instant access.)

This might be a key feature that's missing to enable widespread adoption. With an adaptor to a relational database, most reporting engines will be able to READ from such relational databases for business reporting needs { Dashboards, Emailed PDF reports, adhoc reporting, etc }

It would be best if a "GUN-PostgreSQL" (for example) adaptor project could be managed alongside the core GUN project(s).

Thanks.

**Comment by amark** [comment]
@merarischroeder this is a good idea. I just honestly don't have any time to code it... I'm so swamped with everything else. But <3 <3 <3 <3 if you could help with this.

Could we by chance maybe move this as a feature-request to the JOY repo or the official https://github.com/gundb/feature-requests link? GitHub is starting to report GUN as having "100 Issues" when most of these are questions/features, not actual bugs, and I don't want people thinking "wow that is a lot of issues". So can I close this, since it isn't a bug? I want the conversation to continue, but probably StackOverflow? Closing... reopen if need be! Thanks!

**Comment by merarischroeder** [comment]
Done - moved to feature-requests repo
