### ISSUE TITLE
Running GUN with multiple servers and a single data store

### ISSUE THREAD

**Issue by mitra42** [amark/gun#723]
We (Internet Archive) are running GUN in a docker instance under Kubernates - which can power up servers as required for load, in case of failure etc, but has a number of constraints.

In order to persist GUN across times the server is restarted we mount the data store from a persistent storage volume.

We'd like to configure Kubernates to spin up multiple servers if load spikes (as it does whenever someone does a live demo of dweb.archive.org for example). BUT I'm concerned that two servers hitting the same data store would corrupt it and can't find any info (https://github.com/amark/gun#docker being the obvious place).

Is running this kind of installation covered anywhere, or is it too weird to be common - in which case does anyone know whether GUN for example uses appropriate locks to stop conflicts when two or more servers share a data store ?

Note that we are almost entirely using GUN (on this box) with a hijacker that grabs gun addresses like /arc/archive.org/metadata/foo and redirects them to a HTTPS query.

**Comment by amark** [comment]
@mitra42 running separate gun processes on the same folder or files can cause corruption.

This is absolutely an issue.

I had chosen to leave that as something to be added after I could prove the storage engine (RAD) was reliable for single process use cases (I have not been able to yet, go1dfish uses a Redis adapter instead of RAD for storage in production). In order to isolate bugs during development.

If it can be avoided, I've instructed others to just run separate peers with their own copies of the data, and use gun to sync them,

However if this needs to be prioritized, I'm working on RAD now anyways, and have several PTSD and PANIC tests for it. We could design a test for this today at our meeting, and that would give me numbers to benchmark and correctness test against.

**Comment by amark** [comment]
@mitra42 I have patched this that if you run multiple GUN instances within the same NodeJS process it will reuse/share the same RAD storage calls.

There is no plan to support separate concurrent NodeJS processes read/writing from the same data folder, as concurrency control is GUN's specialty not RAD's, so the solution would be to save to different folders and use GUN to sync those folders.

As a result, it probably doesn't do much good to keep this issue open long-term, now that I at least make sure same-process multiple GUN instances don't corrupt each other - so I'm gonna treat this as fixed.

If anybody has some good arguments as to why this should not be considered the case, please speak up and reopen!
