### ISSUE TITLE
GUN as Distributed DNS? ( Re: Australian DNS block of d.tube )

### ISSUE THREAD

**Issue by Abul22** [amark/gun#729]
In light of seeing and experiencing the ease of censoring (arguably content that should be blocked - but not at the cost of blanket blocking everything on the website or server) - politics aside though, lets talk what's possible with this awesome creation.

I'm a very inexperienced dev - so please forgive the lack of technical clarity in what I'm trying to describe/ask.

Would GUN be a suitable stand in for the creation of a distributed DNS (or even site data hosting!?) -- 

I'm imagining either people are hosting servers that pull DNS lookup tables from multiple providers and then majority consensus of that dns lookup is what's used by users
(Though that's missing economic incentive to host those servers :/ )

Or like a overlay GUN internet... Gunternet...Gunnet...GUNWEB...Ha, idk.

Concept: Sites acting as the initial bootstraps for users to get peers and then as a user you're just querying the GUNDB to browse... Either for the IP of the lookup name to view on the normal net, or as the actual endpoint for the site's (static only?) data.

gun.get('d.tube') 
returns eg.
{
IP: 1.2.3.4 
Alt/mirror-urls : ["a.com","b.com"..]
StaticPageData? : ['<html></<html>']
checksumAuthenticity: 3D32FFsafsa
}
...Or something like that for each url in the alt/mirror arr.
With the GUN DNS lookup table being populated and maintained magically by p2p consensus...Somehow.

I'd also like to give a shout out to this project that I believe may have a decent set of complementary uses with gun and achieving that dream of a properly distributed web https://github.com/chr15m/bugout

Thoughts?
Rambling fool? Or something that could actually be created and work...

Cheers :+1:

**Comment by amark** [comment]
@Abul22 totally possible! And not rambling, it is a great idea!

Especially with several people in the community already testing multicast discovery, you could do some really cool stuff.

I'm not much of a fan of the domain model tho, I think any "name" should be powered by Identifi/Iris or be a type of search, rather than "owned" by somebody globally. BUT that is a separate debate. A few years ago, I recall 2 teams wanting to start this as well, tho they never showed any code.

This would be awesome if you'd build it!!!!

(also, any chance we could move this into a StackOverflow or something? GitHub is starting to report GUN as having "100 Issues" when most of these are questions/features, not actual bugs, and I don't want people thinking "wow that is a lot of issues". So can I close this, since it isn't a bug? I want the conversation to continue, but probably StackOverflow? Closing... reopen if need be! Thanks!)
