### ISSUE TITLE
function require

### ISSUE THREAD

**Issue by ShareTheWorld** [amark/gun#736]
I want to have a public location at gun, everyone can store the data in, everyone can see the data, but only the publisher can modify and delete this data, can gun achieve such a function?

**Comment by amark** [comment]
@ShareTheWorld you could enforce this with an adapter, the site notabug.io is kinda similar to what you are saying (but no publisher).

The community is super friendly and can probably help you get started with this at https://gitter.im/amark/gun ! GitHub issues are meant for bug reports, since most help happens on the chat room and gets much much much much faster replies. Gonna close this - see you on the chat!
