### ISSUE TITLE
How do I get length of elements in Gun Set? 

### ISSUE THREAD

**Issue by sachinsawant71** [amark/gun#764]
Consider following example -

var gun = Gun();
var sam = gun.get('sam').put({name: "Sam"});
var rob = gun.get('rob').put({name: "Rob"});
var bob = gun.get('bob').put({name: "Bob"});
var dave = gun.get('dave').put({name: "Dave"});

sam.get('friends').set(rob);
sam.get('friends').set(bob);
sam.get('friends').set(dave);

How do I count number of Sam's friends without iterating it through sam.get("friend").map()? 

Something like javascript array's length attribute?

**Comment by amark** [comment]
@sachinsawant71 this would be better as a https://stackoverflow.com/questions/tagged/gun question. Could you port it and my answer to SO please?

Quick code:
```
gun.get('friends').once(function(list){ console.log(Object.keys(list).length - 1) });
```

`- 1` because `list` has `_` metadata property on it.

@sachinsawant71 are you new to the community? :) :) :) WELCOME!!! Please do hop on the community chat https://gitter.im/amark/gun to get more help and tell us about your projects!
