### ISSUE TITLE
Recall stores username & password in plaintext.

### ISSUE THREAD

**Issue by TensorTom** [amark/gun#777]
Over [here](https://github.com/amark/gun/blob/8431dce0b9f57b98ceeb844f071bc278387905c0/sea/create.js#L76) we have code to handle auth/reauth. Reauth gives us a sort of session but it stores user's password in plaintext. This should be changed to encrypt the recall data with a temporary key that we can expire.

I will try to work at it. Suggestions welcome. We can't really do session tokens or anything like that without introducing a third-party trust mechanism. So let's not do that but we can at least encrypt the data with a temporary key that we can destroy. Or maybe someone has a better idea.

**Comment by amark** [comment]
Thanks for this @TensorTom , I'm willingly up to obfuscate it, please PR!

 > Note: This is in browser, only on the user's device. Passwords are never sent to servers or other devices.

Tho it unfortunately obfuscating here won't do much good :/ because these are actually the sucky limitations of the browser for session management.

(A) plaintext is only per-session (tab refresh) in the users browser, it gets wiped when the page exits. So it isn't actually being stored.

(B) if we obfuscate it, the encryption key itself has to be stored in plain text. Bleh!!!!

:( :( :( :( so plaintext is unavoidable here due to browser APIs :( :( :( :(

I gave a pretty detailed rundown of all this in this:

https://stackoverflow.com/questions/53578591/keeping-a-gun-db-user-authenticated-during-a-session

I'm gonna close. But will happily accept a PR that obfuscates things, just please be aware it won't really provided any additional security, but it'll certainly make me *feel* better.

Please reopen if you know of some other Browser API we can use to get around this limitation.
