### ISSUE TITLE
gun.put(`SEA{}`) not working

### ISSUE THREAD

**Issue by mimiza** [amark/gun#822]
Hello amazing people. I am encountering a very weird issue. It looks like a bug, doesn't it? I can't tell if this is a bug or it is there by design. Let's assume that I have imported sea.js, and /lib/promise.js. Now I go to browser console and put this code:
```
// GUN version: 0.2019.915

gun.get('user').on(data => console.log(data))
;(async () => {
var pair = await SEA.pair()
var sign = await SEA.sign('hello', pair)
await gun.get('user').get('myusername').put(sign) // TEST 1: gun.on fires as usual, but the data is not found
await gun.get('user').get('myusername').promPut(sign) // TEST 2: gun.on fires as usual, but the data is not found
await gun.get('user').get('myusername').promPut(`SEA{}`) // TEST 3: gun.on fires as usual, but the data is not found --> WTF?
await gun.get('user').get('myusername').promPut(`@SEA{}`) // TEST 4: adding a random letter (@) before `SEA{}`, gun.on fires as usual, AND THE DATA IS FOUND!
await gun.get('user').get('myusername').promPut(`hello world`) // TEST 5: gun.on fires as usual, DATA IS FOUND!
})()
```
THERE WAS NO ERROR RETURNED. Everything seems working, but just doesn't really work. Without being able to save encrypted/signed data... No, I believe this is a bug.

Thanks for reading,
Shan.

**Comment by amark** [comment]
Yes, this is absolutely a bug.

And a pretty bad one for anyone needing to do private data. 

It *should* be a super simple fix, but I gotta keep focused on storage stability and scalability (I think I finally have the answer and solution!)

Anybody who can fix this would be my hero. I can even sit down with them to explain where and how, if they're willing to get 3+ people in the community to join a call, record, and help.

This bug is also reported here https://github.com/amark/gun/issues/783 could we merge them by either close that old one or close this so we only have 1 place to track it?

Thanks for reporting this @mimiza it's very important people complain about anything remotely odd or strange so they can be smoothed out and improved over time.

**Comment by mimiza** [comment]
Hey thanks for being so fast on giving FREE SUPPORT! Yay! You can point out where the issue is and maybe I could fix it, but not promising anything, I just try. Thank you.

**Comment by Lightnet** [comment]
You may want to add JSON.stringify() to call that convert to string and window.btoa(str); gun root graph will reject it I think when I was testing but user root should be fine.

https://www.w3schools.com/jsref/met_win_atob.asp

**Comment by mimiza** [comment]
@Lightnet saving SEA to user root has its own problem. The data is saved and can be found but it is somehow broken, different from the original data, as mentioned by someone in the gitter chat room.

@amark feel free to close this issue, thank you.
