### ISSUE TITLE
Verify CJS/AMD/ESM/other module/environment working with GUN

### ISSUE THREAD

**Issue by rm-rf-etc** [amark/gun#824]
Related issue: https://github.com/amark/gun/issues/789

I think that importing Gun only works via script tag (because of globals) and via CommonJS imports (meaning NodeJS and Browserify). I tried importing SEA in the StackBlitz editor tonight and it didn't work. I think this happens because StackBlitz expects libraries to export the default export as a property named `default`. This is a common stumbling block between CJS and ESM. In ESM, `export default thing` is equivalent to `exports.default = thing` in CJS, not `module.exports = thing`, as we might expect. But this *is* done in bundler systems.

# The Problem
Gun code exports *only* via CommonJS modules, and global objects. These are essentially not standard anymore.

# CommonJS
CJS was the go-to solution in the past thanks to Browserify. It became easy to package modules for both NodeJS and the browser this way.
## Why We Need CJS
NodeJS is still a CJS hold-out.
## Why CJS Isn't Enough By Itself
Nobody uses Browserify anymore (except for legacy projects). Webpack beat Browserify on performance and flexibility, plus Browserify was *only* for CJS. As soon as ES Modules became standard, Browserify was no longer needed.

# AMD
Mostly just used by legacy projects, to my knowledge.
## Why We Need AMD
Some users may have a hard dependency on AMD at their company, and using Gun would not be an option for them without some sort of module adapter (what a pain).
## Why AMD Isn't Enough By Itself
AMD is the most dated of all. Nobody likes AMD.

# Globals
Globals used to be the only option. It used to be that we considered a global object to be a namespace, and we attached our classes and objects to these. It was this way because we had no choice.
## Why We Need Globals
Globals are mostly only useful for quick demos, when we want to add our library to a static page using a script tag. Most projects will grow out of this quickly and switch to a module bundler in order to manage growing complexity. Also, the popularity of this approach for quick trials is on the decline, thanks to projects like Yeoman, Create React App, and code environments like StackBlitz, Codepen, etc, it's becoming more common to install an npm module and import it using ES Module syntax.
## Why Globals Are Bad
- http://wiki.c2.com/?GlobalVariablesAreBad
- [Globals Are Evil](https://www.youtube.com/watch?v=Ov2QilGv32Y)
- Developers using Gun have no way to opt out, they have no choice but to inherit these globals.
- They make it easier for bad actors to execute arbitrary commands from the console because the Gun constructor is already in scope.

# Proposed Solution
It looks like anyone expecting Gun to import correctly via ES Modules or AMD modules will have an unpleasant surprise. I want to prevent that.

Webpack has a process that allows us to output a bundle that supports all the mentioned module systems:
https://webpack.js.org/guides/author-libraries/

Let me help update Gun to ES Modules, setup a build process to output bundles with Webpack, and while I'm at it, if you want I can also setup lerna & workspaces to automate versioning and module publishing.

I think we can do all of this and keep the unbuild process so gun.js can remain a single file.

## Benefits We Stand To Gain
- Remove bottlenecks in generating TypeScript typings
- Smaller bundles
- Increased cross-browser support
- Universal module support
- Better adherence to best practices and increased adoption

**Comment by amark** [comment]
### YES!

@rm-rf-etc as you know my philosophy is "be compatible but don't break JS".

One thing that would be tremendously helpful *before* any changes is to show the simplest working example of each system, because a few months ago somebody tried to show me `import` and it didn't work and the person (not me) basically concluded "this is an upcoming browser feature that ". I want to be future-proof, but if I or the other person cannot explain what or how or even get a simple example working, then I'm extremely wary to add it as code - on these subjects, I'm a pragmatist, it must work and be understandable. Full disclosure: Often what happens, if somebody can demonstrate actually working code, that I'm able to experience, I get very excited and giddy - they've truly proven it can be used by a simpleton (me!), most of my life I've been mocked for not knowing how to "oh it is just this CLI, just apt-get, then just sudo foo, just!" and it hurts, so I'd rather hang out with simpletons than pros.

 - Cross-browser/environment support is one of my highest priorities! Thank you for including this!

Which I want to re-emphasize, the addition of new things cannot break old support/compatibility.

So yes, if we can **add** support that'd be super appreciated, I just don't want to change/update/remove existing support.

**Comment by amark** [comment]
we also shouldn't forget about React Native, Nativescript, Electron, Unity/Unreal and even IoT/raspi/ESP8266 support, or anything else. Changing/updating title.

**Comment by rm-rf-etc** [comment]
> we also shouldn't forget about React Native, Nativescript, Electron, Unity/Unreal and even IoT/raspi/ESP8266 support, or anything else. Changing/updating title.

Of course. Going to webpack will ensure these all work, but we'll still need test setups to verify.

Made great progress tonight. Refactored the `USE` module system to more closely match the order of operations we will have under ESM and CJS. This was an important first step. I verified all tests continue to pass while doing this refactoring. Couldn't have done it without the tests!!

I saved my work over a series of branches in case it helps you see how I got to the final result.
https://github.com/rm-rf-etc/gun/tree/esm-pt1
https://github.com/rm-rf-etc/gun/tree/esm-pt2
https://github.com/rm-rf-etc/gun/tree/esm-pt3

Next step is to update unbuild, like I did in the other PR, to inject ES modules.

@amark I had to mark the `refresh login` test for `sea.js` with `.skip`, because it always fails for me when I run the full test suite, but it succeeds if I run it by itself. I tried increasing the wait time but that's not the issue. The callback for `user.auth(` is invoked with different inputs depending on some unknown race condition.
![Screenshot 2019-09-30 03 43 13](https://user-images.githubusercontent.com/5067463/65872149-d0a83580-e334-11e9-838a-c5966f5d85e8.png)
![Screenshot 2019-09-30 03 46 33](https://user-images.githubusercontent.com/5067463/65872210-ee759a80-e334-11e9-9591-1fe92ccf6b4d.png)
![Screenshot 2019-09-30 03 48 35](https://user-images.githubusercontent.com/5067463/65872341-33013600-e335-11e9-8d71-ed3ca7e62588.png)
![Screenshot 2019-09-30 03 49 20](https://user-images.githubusercontent.com/5067463/65872397-4dd3aa80-e335-11e9-8e48-505d45f8beba.png)

**Comment by robchristian** [comment]
> One thing that would be tremendously helpful _before_ any changes is to show the simplest working example of each system,

When you say "working example", do you mean specifically with Gun, or just some example of ES modules? Part of the challenge for me in applying ES modules to Gun, has been knowing the order in which the parts of Gun need to be initialized, so I needed to get this sorted out before I could do something like create an example of Gun with only ES modules.

Also, to answer a question you asked in Gitter, ESM import statements can't be wrapped in try/catch blocks because they aren't expressions like `require()` is. ESM has more limited rules. For example, all import statements *must* happen before any other code in the file.

**Comment by amark** [comment]
(1) simplest example, regardless of GUN, like module A & B, where A is addition and B is hello world.

(2) Order follows exactly the sequence as gun.js

(3) shoot, that sounds terrible & problematic :/ but ... I'm not gonna fret until (1) cause I bet there is some tricks we can do. If there is a will, there is a way!

**Comment by rm-rf-etc** [comment]
```javascript
// hello.js
export default () => {
  console.log("Hello world")
}
export const helloName = (name) => {
  console.log(`Hello ${name}`)
}
```
```javascript
import hello, { helloName } from "./hello.js"

hello() // Hello world
hello("Mark") // Hello Mark
```

**Comment by rm-rf-etc** [comment]
We'll only use ES modules in the unbuild results, so it will all work.

**Comment by Jack-Works** [comment]
a better way to publish the package is ESModule + UMD.

UMD supports AMD, System, CJS or no module system at all.
