### ISSUE TITLE
Fix the variable/function names to be less ambiguous

### ISSUE THREAD

**Issue by DaveWelling** [amark/gun#842]
https://medium.com/coding-skills/clean-code-101-meaningful-names-and-functions-bf450456d90c
I cannot debug this code because it looks like there was some convention that every variable or function name has to be <= 5 characters.  Was this written on 70x40 green screen?
It will be far easier to attract an audience of capable developers to aid in maintaining the code if things in the code are given less ambiguous names.

**Comment by amark** [comment]
It is common notation in mathematics, but not coders. At this time, the math being correct is more important than how the code looks.

Mathematical notation lets you compress more information into less space which lets mathematicians reason about higher order complexity in fewer steps. Coders do the opposite, they express less logic in more space to deal with or handle the complexity.

Also, most of the functions and variables don't do anything specific, their logic is equally as abstract, which is why GUN can do & scale so much on so little code. I'd honestly need to do a video call with people and have them tell me what the variable should be named after explaining the algorithm.

If you'd like to do that, please let me know by reopening the issue (if GitHub lets you do that? Or tag me to reopen it).
