### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by metasean** [amark/gun#89]
Support a schema record.  Each field in a schema would have the following properties:  
 - name (required) any object using the schema would have the same name
 - JavaScript or plugin type (required) initially would support JavaScript object types  'string', 'int', 'date', 'boolean', but could be extended to support custom types (e.g. map object could include latitude and longitude)
 - description (optional) primarily for documentation purposes
 - validation (optional) must account for XSS

Schemas could be used for tabular or document based objects.  Any object based on the schema would need to use the same names:
```
{ schema: { 
      A: { name: 'first-name', type: 'string', val: 'string at least 3 chars no more than 21 chars' } 
      A: { name: 'date-of-birth', type: 'date' } 
   },
   ASDF: { A: 'Bob', B: '345678098765' },
   FDSA: { A: 'Dan', B: '987654456789' }
}
```

The scheme does not need to be embedded in the metadata, it can be by reference.

**Comment by RangerMauve** [comment]
[json-schema](http://json-schema.org/) would be perfect for this, and there are some [useful](https://github.com/mafintosh/is-my-json-valid) validators that could be used for this.

**Comment by metasean** [comment]
@RangerMauve  - Thank you for pointing out json-schema! We're debating whether to have a simple gun extension or use something like json-schema.

**Comment by amark** [comment]
+1 @RangerMauve . I'm always about reinventing wheels but I do agree that it is pointless to make our own. The annoying part though is that we then need an adapter for each and every existing popular implementation (in the same way we need an adapter for Angular, React, Ember, Aurelia, Backbone, Famous, Polymer, etc.), and I don't know how well those libraries (the schema/validators ones) integrate with other projects.

Does anybody know? Anybody interested in contributing their favorite validator? I'll help them get setup with making a gun extension for it!

**Comment by RangerMauve** [comment]
In my experience json-schema is pretty standard and the validator I linked to is one of the most minimal and performative ones being actively maintained. If there are some hooks you could point me to I'd gladly add the extension

**Comment by amark** [comment]
@RangerMauve I thought there was json-schema as well as Mongoose's validator (which is baked into their project, but fairly popular?).

Yes! Okay, I need to actually document this well somewhere else... but for now I'll inline it:

```javascript
var Gun = Gun || require('gun');

Gun.chain.save = function(val, cb){
	var gun = this;
	
	if(val === "Robert'); DROP TABLE Students;--"){
		cb({err: "You cannot Bobby Drop Table me!"});
	} else {
		gun = gun.put(val);
	}
	
	return gun;
}
```

Now you have wrapped `.put` with a higher level abstraction that has better safety and security. And you can use in your app, after you've included in the server or browser, like such:

```javascript
var gun = Gun().get('student');
	
gun.path('name').save("Robert'); DROP TABLE Students;--");
```

Obviously you need to know how the rest of gun works to make extensions that are actually useful. But it is super easy to extend gun like extending jQuery.

I need to turn this into its own article/tutorial with more detailed instructions and examples. But as for now, do you have any questions? What else can I help with? I'm super excited for you to help contributing modules/extensions/whatever!

**Comment by RangerMauve** [comment]
Mongoose's validation is pretty good, too. But I haven't seen anyone use it outside of Mongoose and am not sure how easy it would be to make it general purpose.

I like the xkcd reference. :P

I think the convention for something like this is either to have Gun expose a method that would add the plugin, or have the plugin be a function that takes the Gun instance and modify it that way. For now I'll go with the latter.

Another question is where I can store state in a gun instance for keeping track of which schemas go where. Should they be nodes in the actual graph? And how do I know what nodes will get the schema applied to them? Or is it that the schema would apply to everything?

I'm currently in the process of moving so I'll probably only have time some code down on Sunday.

**Comment by amark** [comment]
@RangerMauve What's wrong with your internet? Do you need help getting it back?

**Comment by RangerMauve** [comment]
I just moved and Canadian ISPs aremail kinda cappy so it's taking a while to set up.

**Comment by RangerMauve** [comment]
Alright. After getting the net back I was super busy so I've just now got a day free to devote to this. Are you imagining this as there being a single schema that applies to every node in the graph? Or would `save` pontentially take a `type` argument so that one could specify multiple different types of nodes and vaildate against whatever one you're trying to create?

I was thinking there could be something like

* `gun.type(type, json_schema)` : Takes a name for the type and the schema instance and saves it internally
`gun.save(type, value)` : Takes a name for the type of node you want to save, and validates it against the schema before putting it into the graph.
`gun.typeOptions(options)` : used to configure the validation library, probably [is-my-json-valid](https://github.com/mafintosh/is-my-json-valid)

What do you think?

**Comment by amark** [comment]
Yay! So excited, thanks so much. I think the `gun.type` approach is more flexible. Although I know most people use Mongoose, and I'm not sure how they do it - so that might work better. But also, I would design it however you think will best solve people's schema needs, from whatever personal experience you've had trying to use schema before.

**Comment by amark** [comment]
*oops, clarity of answer: I definitely don't think a single schema should apply to every node, but instead apply to specific nodes.

**Comment by RangerMauve** [comment]
The way Mongoose does it is by having users define model instances. They have you create a new schema instance by passing an object literal to `mongoose.schema`, then they have the user passing that to `mongoose.model` which returns the actual model which you then perform queries with. I like their approach for something like MongoDB where there are distinct collections, but I think it'd be less useful for a graph DB like GUN.

Another thing, I was thinking that I'd use the prototype chain for taking in an instance of gun and returning an object with that instance as it's prototype but with the added methods (Using `Object.create`). That way you'll have access to all the methods of gun but with the added stuff. Since I'm still pretty fuzzy about how the implementation works, do you think you could tell me if that approach will work or if I'd need to go at it from a different angle?

**Comment by RangerMauve** [comment]
Alternately I was thinking of just having an `addSchemas(gun)` function that'd just add the needed methods to a gun instance.

**Comment by amark** [comment]
I typically automatically attach / listen / or extend from gun because IF somebody either `require('gun-schema')` or `<script src="./gun-schema.js">` then they are already wanting it to be included, and it seems unnecessary to have to take the "extra step" of then also calling `addSchemas(gun)`.

An example was my **old code** for `.set()` which was in a separate file: https://github.com/amark/gun/blob/master/lib/set.js .

If you do something like:

```
var Gun = Gun || require('../gun');
Gun.chain.schema = function(){}
```

You extend gun, and your library gets automatically attached to every new gun instance. Should work in both client/server (although there are some minor exceptions, super old versions of IE don't like the overriding a global).

**Comment by amark** [comment]
Oh, I missed your earlier message. Yeah, good points on Mongoose, I think you are right. And oops! I accidentally answered how to assign to the prototype in my above message. `Gun.chain` is the prototype.

**Comment by RangerMauve** [comment]
Cool, so gun extensions are made to always extend the global Gun instance. Is there any potential for that conflicting in projects where one might want instances of gun which have different configurations, or do you think that's likely outside the scope of the current implementation?

**Comment by amark** [comment]
Sorry, clarification... it doesn't extend `Gun` itself, it extends the instances of gun, because of the prototype. But yes, this would effect every instantiation and wouldn't allow for sub-configurable ones.

IF you want to only do it for sub-configurable ones, you add it as it is a hook (how my websocket, JSONP, and server side modules work):

```
var Gun = Gun || require('../gun');
Gun.on('opt').event(function(gun, opt){
    // gun is an individual gun instance which you can attach to.
    // and opt is the user's specific configuration requests for this instance.
});
```

**Comment by amark** [comment]
I'm leaving for the day though, so I won't be around for the next several hours.

**Comment by RangerMauve** [comment]
I'd rather align with the current ecosystem rather than making stuff up so I'm going to follow your initial example. :D  I think that's all I'll need for the initial implementation. Have a good day.

**Comment by amark** [comment]
wonderful thanks! I'll be back later so please make sure to message me with any questions so I can answer them when I get back.

**Comment by amark** [comment]
(fyi the current ecosystem... like websockets, jsonp, serverside do use the more recent code, not the earlier code. Then the API commands extend from the chain prototype, like `set` and stuff) bye!

**Comment by RangerMauve** [comment]
I guess there is another thing. I see that you wanted to have a CB get called rather than throwing an error right away, what's the reasoning behind that? I was under the impression that it would be good to fail early.

**Comment by RangerMauve** [comment]
[Here's](https://github.com/RangerMauve/gun-schema) the initial implementation. Do tell me what you think. If it's good, then I propose forking it to the org and maintaining it there after I give everyone publish rights to the npm package.

**Comment by amark** [comment]
Wow! Just tried it out, actually played with it in the browser. Worked like a charm. This is fantastic!

This could also be really important for loading data, gun streams out data piece by piece, but sometimes you want to know when you've received the whole data - having a schema would allow us to check, and wait for the full object before returning it to the user.

Sorry I didn't do this earlier! Just sent you an invitation to be a contributor to the org. I'll continue any comments as issues/pull requests on the project. Thanks so much, super stoked! I also updated the gun readme and wiki to include your module. It was only a fast update, I'll add more later!

I'm also going to consider this issue "closed" for now. :) With all subsequent issues regarding "schema" as pointing toward this!

**Comment by RangerMauve** [comment]
Sick! Gimmi a list of npm handles so I can add y'all to be able to publish to it when needed.

**Comment by amark** [comment]
npm handles? Like our npm usernames? I think mine is the same as github, "amark". Not sure about others.

**Comment by RangerMauve** [comment]
Cool. Also, do you think you could do the fork to the org so that it could live there instead? :D

**Comment by amark** [comment]
absolutely! I should be able to do it within the next few days. (I'm actually kinda bad with git, although forking is pretty easy.)

**Comment by RangerMauve** [comment]
Sounds good. I might get around to some of the other things on the checklist when I have time for it. I'll probably just try to make the repo right in to org for the next one, though. Easier that way.

**Comment by amark** [comment]
:D

**Comment by metasean** [comment]
Forked - https://github.com/gundb/gun-schema

**Comment by RangerMauve** [comment]
@metasean Mind enabling issues in the repo as well, then I'll disable it in the original one and add a note about the move.

**Comment by amark** [comment]
Oh, thanks @metasean for doing that. @RangerMauve you want me to update the other links to now point to that one?

**Comment by RangerMauve** [comment]
@amark Yeah, that'd be a good idea. :o

**Comment by amark** [comment]
done! Thanks. :D

**Comment by metasean** [comment]
@RangerMauve - Issues enable on https://github.com/gundb/gun-schema .  Thanks for pointing that out that it needed to be done!
