### ISSUE TITLE
GunDB completely decentralized

### ISSUE THREAD

**Issue by snapo** [amark/gun#960]
Hi I remember around a year ago reading about GunDB dosent need a server... that is true if the service did run at least once... But is there already full integration / backup to ipfs?

That means hosting everything on IPFS without any centralized server?

Best regards

**Comment by sirpy** [comment]
not at the moment. but i can be quite simple to persist gun into ipfs.
gun has storage adapters, currently their interface is
put(key,value)
get(key)
so you just need to implement them to write and fetch from ipfs

**Comment by amark** [comment]
Thanks @sirpy for that tip!

@snapo IPFS definitely more centralized than GUN. If you're running NodeJS, GUN is fully decentralized with UDP multicast and mesh networking. Browsers do not allow this tho (not our fault), but we circumvent that with WebRTC and p2p relays that act like internet switches/routers.

Closing, since by default, GUN runs in decentralized/p2p mode. In browsers: avoid 1 peer, use 3+.
