### ISSUE TITLE
text-encoding package no longer maintained

### ISSUE THREAD

**Issue by marcoippolito** [amark/gun#989]
I get this warning: gun > text-encoding@0.7.0: no longer maintained

And actually looking at the npm repository:
https://www.npmjs.com/package/text-encoding : This package has been deprecated

I yarn removed this packaged but now I get: warning " > gun@0.2020.520" has unmet peer dependency "text-encoding@^0.7.0"

**Comment by amark** [comment]
@marcoippolito `text-encoding` is considered "final", bug-free, and exact-to-spec & thus "archived" since its a shim for what browsers should already do (but ?NodeJS? doesn't have). This scares devs, when it shouldn't, but none-the-less, we should get it resolved: Would someone be willing to copy text-encoding into `gun/lib/text-encoding/*` and then update dependency to pull from local copy rather than external?
