### ISSUE TITLE
Move tmp file to subfolder

### ISSUE THREAD

**Issue by septs** [amark/gun#994]
related code?
https://github.com/amark/gun/blob/5cbd5e394325a987c0ef50284e5bd99be66d21b3/lib/rfs.js#L16-L25

current state:
![image](https://user-images.githubusercontent.com/3842474/89127870-c55d0200-d523-11ea-9b0d-2b48e9e022cd.png)

expected folder structure:
```
/radata
/radata-tmp
```

**Comment by septs** [comment]
my expected

```patch
diff --git a/lib/rfs.js b/lib/rfs.js
index e61d2f5..7ea569f 100644
--- a/lib/rfs.js
+++ b/lib/rfs.js
@@ -16,7 +16,7 @@ function Store(opt){
        store.put = function(file, data, cb){
                puts[file] = data;
                var random = Math.random().toString(36).slice(-3);
-               var tmp = opt.file+'-'+file+'-'+random+'.tmp';
+               var tmp = opt.file+'/'+file+'-'+random+'.tmp';
                fs.writeFile(tmp, data, function(err, ok){
                        delete puts[file];
                        if(err){ return cb(err) }
```

**Comment by septs** [comment]
![image](https://user-images.githubusercontent.com/3842474/94648749-bfb64980-0325-11eb-8738-b66cfb4b60c5.png)

**Comment by septs** [comment]
@amark hope to fix this bug.

tmp file in radata outside.

**Comment by amark** [comment]
@septs yes, but:

1. putting it inside `radata` might mess up directory listing.
2. putting it in another folder is good, but have to make sure NodeJS won't crash "folder does not exist"
3. More importantly, these `.tmp` files mean something far worse is going on. :/ They won't get cleaned up automatically yet, and they mean writes failed, so that data is being "lost" (browser should get an error)

**Comment by septs** [comment]
UNSOLVED
